import { Scholarship } from '@/types';

/** Fully source-backed original 12 scholarships */
export const ORIGINAL_12_A: Scholarship[] = [
  {
    id: '1',
    title: 'Chevening Scholarships',
    officialName: 'Chevening Scholarships and Fellowships',
    university: 'Various UK Universities',
    country: 'United Kingdom',
    countryCode: '🇬🇧',
    degreeLevel: ['Master'],
    fundingType: 'Fully Funded',
    deadline: '2026-11-05',
    isDeadlineEstimated: true,
    description: 'Chevening is the UK government\'s international awards programme funded by the Foreign, Commonwealth and Development Office (FCDO). It offers one-year master\'s degree scholarships to individuals with leadership potential from Chevening-eligible countries.',
    eligibility: [
      'Citizen of a Chevening-eligible country or territory',
      'Return to your country of citizenship for a minimum of two years after the award',
      'Have an undergraduate degree equivalent to an upper second-class 2:1 honours',
      'Have at least two years (2,800 hours) of work experience',
      'Apply to three different eligible UK university courses and receive an unconditional offer from one',
    ],
    benefits: [
      'University tuition fees (capped at a set rate)',
      'Monthly living allowance',
      'Economy class return airfare',
      'Arrival and departure allowances',
      'Cost of one UK visa application',
      'A travel grant to attend Chevening events',
    ],
    coverageDetails: [
      'Full tuition fees (capped amount)',
      'Monthly living allowance',
      'Economy class return airfare',
      'Arrival and departure allowances',
      'One visa application cost',
    ],
    requirements: [],
    requiredDocuments: [
      'Completed online application form',
      'Undergraduate degree transcript and certificate',
      'Two references (academic and professional)',
      'Valid English language test score (IELTS, TOEFL, or equivalent)',
      'Personal statement',
      'Valid passport',
    ],
    applicationProcess: [
      'Check eligibility at chevening.org',
      'Submit online application during the application window (usually August–November)',
      'Shortlisted candidates are interviewed at the British Embassy/High Commission',
      'Apply and receive unconditional offers from three UK universities',
      'Successful candidates are notified around June',
    ],
    selectionCriteria: [
      'Demonstrated leadership and influence',
      'Strong networking skills',
      'Clear career plan and commitment to return home',
      'Academic excellence',
    ],
    applicationTips: [
      'Write four strong essays — they are the core of the application',
      'Choose three universities strategically, not just by ranking',
      'Demonstrate two-way benefit: how the UK benefits from you too',
      'Show concrete leadership examples with measurable impact',
    ],
    languageRequirements: ['IELTS 6.5 overall with minimum 5.5 in each component, or equivalent TOEFL/PTE score'],
    applyUrl: 'https://www.chevening.org/scholarships/',
    officialSourceUrl: 'https://www.chevening.org/scholarships/',
    lastVerified: '2026-04-30',
    sourceNotes: 'Application window typically opens August and closes November. Exact dates confirmed annually on chevening.org.',
    featured: true,
    tags: ['UK', 'Postgraduate', 'Leadership', 'Government'],
    hostCountry: 'United Kingdom',
    category: 'Government',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Fulbright Foreign Student Program',
    officialName: 'Fulbright Foreign Student Program',
    university: 'Various US Universities',
    country: 'United States',
    countryCode: '🇺🇸',
    degreeLevel: ['Master', 'PhD'],
    fundingType: 'Fully Funded',
    deadline: '2026-10-15',
    isDeadlineEstimated: true,
    description: 'The Fulbright Foreign Student Program enables graduate students, young professionals, and artists from over 160 countries to study or conduct research in the United States. The program is administered by binational Fulbright commissions/foundations or U.S. embassies, and requirements vary by country.',
    eligibility: [
      'Citizen of a country with a Fulbright program',
      'Hold a bachelor\'s degree or equivalent by the start of the grant',
      'Sufficient proficiency in English to undertake the proposed study',
      'Meet country-specific eligibility requirements set by the local Fulbright commission',
    ],
    benefits: [
      'Tuition and required fees',
      'Monthly maintenance stipend',
      'Round-trip international travel',
      'Health and accident insurance',
      'Book and equipment allowance (in some cases)',
    ],
    coverageDetails: [
      'Full tuition and required university fees',
      'Monthly living stipend',
      'Round-trip international airfare',
      'Health and accident insurance',
    ],
    requirements: [],
    requiredDocuments: [
      'Online application through the local Fulbright commission or U.S. Embassy',
      'Academic transcripts from all institutions attended',
      'Three letters of recommendation',
      'Study/research objective statement',
      'Personal statement',
      'English language test score (TOEFL/IELTS)',
      'GRE scores may be required depending on the field',
    ],
    applicationProcess: [
      'Contact the Fulbright commission or U.S. Embassy in your country for the local deadline',
      'Submit online application with all required documents',
      'Local commission reviews and interviews candidates',
      'Nominated candidates are reviewed by the Fulbright Foreign Scholarship Board in Washington',
      'Final selection and university placement',
    ],
    selectionCriteria: [
      'Academic excellence and achievement',
      'Quality and feasibility of the study/research plan',
      'Leadership potential',
      'Commitment to return and contribute to home country',
    ],
    applicationTips: [
      'Deadlines vary by country — check with your local Fulbright commission early',
      'The study objective must be specific, feasible, and linked to your home country\'s needs',
      'Strong recommenders who know your academic work make a difference',
      'Fulbright values cultural exchange — show genuine interest in the U.S. and cross-cultural engagement',
    ],
    languageRequirements: ['TOEFL iBT or IELTS required; minimum scores vary by programme and university'],
    applyUrl: 'https://foreign.fulbrightonline.org/',
    officialSourceUrl: 'https://foreign.fulbrightonline.org/',
    lastVerified: '2026-04-30',
    sourceNotes: 'Application deadlines and requirements vary significantly by country. Always check with the local Fulbright commission.',
    featured: true,
    tags: ['USA', 'Research', 'Graduate', 'Arts & Sciences'],
    hostCountry: 'United States',
    category: 'Government',
    createdAt: '2024-01-20',
  },
  {
    id: '3',
    title: 'DAAD Scholarships',
    officialName: 'DAAD Scholarships for Development-Related Postgraduate Courses (EPOS)',
    university: 'Various German Universities',
    country: 'Germany',
    countryCode: '🇩🇪',
    degreeLevel: ['Master', 'PhD', 'Postdoc'],
    fundingType: 'Fully Funded',
    deadline: '2026-10-01',
    isDeadlineEstimated: true,
    description: 'The German Academic Exchange Service (DAAD) funds a wide range of scholarships for international students at all academic levels. DAAD offers multiple programme lines including development-related postgraduate courses (EPOS), research grants, and study scholarships.',
    eligibility: [
      'Completed undergraduate degree (bachelor\'s or equivalent) with above-average results',
      'At least two years of professional experience (for EPOS programmes)',
      'Motivation aligned with development goals of home country (for EPOS)',
      'Programme-specific language requirements (German or English)',
    ],
    benefits: [
      'Monthly stipend: €934 (graduates) or €1,300 (doctoral candidates)',
      'Health, accident, and personal liability insurance',
      'Travel allowance',
      'Study and research allowance',
      'German language course allowance if required',
    ],
    coverageDetails: [
      'Monthly stipend (€934 for Master\'s, €1,300 for PhD)',
      'Health, accident, and liability insurance',
      'Travel allowance',
      'Study and research allowance',
    ],
    requirements: [],
    requiredDocuments: [
      'DAAD online application form',
      'Curriculum vitae (tabular format)',
      'Letter of motivation',
      'Two academic reference letters',
      'Certified copies of academic transcripts and degree certificates',
      'Language proficiency certificate (IELTS/TOEFL for English; TestDaF/DSH for German)',
    ],
    applicationProcess: [
      'Search for suitable DAAD scholarship programme on daad.de/en/study-and-research-in-germany/scholarships/',
      'Apply through the DAAD online portal',
      'Some programmes require parallel application to the university',
      'Applications reviewed by DAAD selection committees',
      'Results communicated several months after the deadline',
    ],
    selectionCriteria: [
      'Academic achievement',
      'Quality of motivation letter and study/research plan',
      'Relevance of proposed studies to home country development (EPOS)',
      'Recommendation letters',
    ],
    applicationTips: [
      'DAAD has many different programmes — find the right one for your level and field',
      'The CV must be in tabular (not narrative) format as DAAD requires',
      'Connect your study plan to development impact in your home country for EPOS',
      'Apply to the university programme separately if required',
    ],
    languageRequirements: [
      'English-taught programmes: IELTS 6.0+ or TOEFL 80+',
      'German-taught programmes: DSH-2 or TestDaF 4x4 or equivalent',
    ],
    applyUrl: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
    officialSourceUrl: 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
    lastVerified: '2026-04-30',
    sourceNotes: 'DAAD runs multiple scholarship programmes with different deadlines and requirements. The EPOS deadline is typically October. Check the DAAD scholarship database for your specific programme.',
    featured: true,
    tags: ['Germany', 'Research', 'STEM', 'Arts'],
    hostCountry: 'Germany',
    category: 'Government',
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    title: 'Australia Awards Scholarships',
    officialName: 'Australia Awards Scholarships',
    university: 'Various Australian Universities',
    country: 'Australia',
    countryCode: '🇦🇺',
    degreeLevel: ['Master', 'PhD'],
    fundingType: 'Fully Funded',
    deadline: '2026-04-30',
    isDeadlineEstimated: true,
    description: 'Australia Awards Scholarships are long-term development awards funded by the Australian Government. They aim to contribute to the development needs of Australia\'s partner countries by providing opportunities for citizens of eligible countries to undertake full-time study in Australia.',
    eligibility: [
      'Citizen of a participating country (not Australia or New Zealand)',
      'Not currently serving military personnel',
      'Meet minimum academic and English language requirements of the host university',
      'Have at least two years of work experience (preferred)',
      'Agree to return to home country for at least two years after completing the scholarship',
    ],
    benefits: [
      'Full tuition fees',
      'Return economy air travel',
      'Establishment allowance on arrival',
      'Contribution to Living Expenses (CLE) — biweekly stipend',
      'Introductory Academic Programme',
      'Overseas Student Health Cover (OSHC)',
      'Supplementary academic support',
    ],
    coverageDetails: [
      'Full tuition fees',
      'Return economy airfare',
      'Establishment allowance',
      'Biweekly living allowance (CLE)',
      'Overseas Student Health Cover (OSHC)',
    ],
    requirements: [],
    requiredDocuments: [
      'Online application form through OASIS',
      'Academic transcripts and degree certificates',
      'English language test results (IELTS/TOEFL)',
      'Curriculum vitae',
      'Statement of purpose',
      'Two referee reports',
    ],
    applicationProcess: [
      'Check country-specific eligibility at australiaawards.gov.au',
      'Submit online application through the OASIS system during the open application period',
      'Shortlisted applicants attend interviews and may sit written assessments',
      'Selection panels make recommendations',
      'Successful applicants receive a conditional offer and apply to Australian universities',
    ],
    selectionCriteria: [
      'Academic competence',
      'Professional and personal leadership qualities',
      'Relevance of proposed studies to development challenges in the home country',
      'Potential to contribute to home country development after returning',
    ],
    applicationTips: [
      'Clearly link your study plan to the development priorities of your home country',
      'Two years of relevant work experience significantly strengthens your application',
      'Application deadlines vary by country — check the local managing contractor',
      'Prepare for the interview with specific examples of leadership and community impact',
    ],
    languageRequirements: ['IELTS Academic 6.5 overall (no band below 6.0) or equivalent TOEFL score'],
    applyUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships',
    officialSourceUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships',
    lastVerified: '2026-04-30',
    sourceNotes: 'Application deadlines vary by country. Typically applications open February and close April–May. Check australiaawards.gov.au.',
    featured: false,
    tags: ['Australia', 'Development', 'Postgraduate'],
    hostCountry: 'Australia',
    category: 'Government',
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    title: 'ETH Zurich Excellence Scholarship',
    officialName: 'Excellence Scholarship & Opportunity Programme (ESOP)',
    university: 'ETH Zurich',
    country: 'Switzerland',
    countryCode: '🇨🇭',
    degreeLevel: ['Master'],
    fundingType: 'Fully Funded',
    deadline: '2026-12-15',
    isDeadlineEstimated: true,
    description: 'The Excellence Scholarship & Opportunity Programme (ESOP) supports outstanding students who wish to pursue a master\'s degree at ETH Zurich. The scholarship covers the full cost of living and study, and includes mentoring by an ETH professor.',
    eligibility: [
      'Outstanding academic record (top 10% of graduating class or equivalent)',
      'Bachelor\'s degree from a recognized university',
      'Admitted or applying to a master\'s degree programme at ETH Zurich',
      'Both Swiss and international students are eligible',
    ],
    benefits: [
      'Living costs grant of CHF 12,000 per semester (total CHF 48,000 for 2 years)',
      'Tuition fee waiver',
      'Mentoring by an ETH Zurich professor',
    ],
    coverageDetails: [
      'CHF 12,000 per semester living grant',
      'Tuition fee waiver',
      'Mentoring by an ETH professor',
    ],
    requirements: [],
    requiredDocuments: [
      'ETH Zurich master\'s application',
      'ESOP scholarship application',
      'Curriculum vitae',
      'Two academic reference letters',
      'Bachelor\'s degree transcript',
      'Motivation letter specifically for ESOP',
    ],
    applicationProcess: [
      'Apply for admission to an ETH Zurich master\'s programme by December 15',
      'Submit the separate ESOP scholarship application at the same time',
      'ETH evaluates both applications in parallel',
      'Scholarship decisions are communicated alongside admissions decisions (typically March)',
    ],
    selectionCriteria: [
      'Outstanding academic track record',
      'Quality of the application dossier',
      'Potential for an academic or professional career',
    ],
    applicationTips: [
      'You must be in the top 10% of your class — verify before applying',
      'The ESOP application is separate from the ETH admission application — submit both',
      'A strong recommendation from a professor who knows your research ability is crucial',
      'Apply by the December 15 deadline — there is only one round per year',
    ],
    applyUrl: 'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html',
    officialSourceUrl: 'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html',
    lastVerified: '2026-04-30',
    sourceNotes: 'ESOP application deadline aligns with the ETH master\'s admission deadline, typically December 15.',
    featured: true,
    tags: ['Switzerland', 'STEM', 'Research', 'Excellence'],
    hostCountry: 'Switzerland',
    category: 'University',
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    title: 'Erasmus Mundus Joint Masters',
    officialName: 'Erasmus Mundus Joint Master Degrees (EMJMD)',
    university: 'Multiple European Universities',
    country: 'European Union',
    countryCode: '🇪🇺',
    degreeLevel: ['Master'],
    fundingType: 'Fully Funded',
    deadline: '2026-01-15',
    isDeadlineEstimated: true,
    description: 'Erasmus Mundus Joint Master Degrees are prestigious, integrated, international study programmes delivered by consortia of universities from different countries. EU-funded scholarships are available for the best students applying worldwide.',
    eligibility: [
      'Hold a bachelor\'s degree or equivalent recognised by the consortium universities',
      'Open to students worldwide (both EU and non-EU)',
      'Specific entry requirements vary by each EMJMD programme',
      'English or other language proficiency as required by the programme',
    ],
    benefits: [
      'Contribution to participation costs (tuition) up to €9,000/year for Partner Country students',
      'Monthly allowance of €1,400 for the entire duration of the programme',
      'Contribution to travel and installation costs',
      'Joint or double degree from multiple European universities',
    ],
    coverageDetails: [
      'Tuition contribution up to €9,000/year',
      'Monthly living allowance of €1,400',
      'Travel and installation contribution',
      'Joint/double degree from consortium universities',
    ],
    requirements: [],
    requiredDocuments: [
      'Application to the specific EMJMD programme consortium',
      'Bachelor\'s degree transcript and certificate',
      'CV/resume',
      'Motivation letter',
      'Letters of recommendation (number varies by programme)',
      'Language proficiency certificate',
    ],
    applicationProcess: [
      'Browse the EMJMD catalogue on the European Commission website',
      'Apply directly to the consortium running the programme of interest',
      'Each programme has its own application portal and requirements',
      'Selection is done by the consortium, not by the EU centrally',
      'Scholarship decisions are communicated by the consortium',
    ],
    selectionCriteria: [
      'Academic excellence',
      'Motivation and fit with the programme',
      'Professional experience (for some programmes)',
      'Criteria vary by individual EMJMD programme',
    ],
    applicationTips: [
      'Each EMJMD programme is different — read the specific programme requirements carefully',
      'Apply to multiple EMJMD programmes to increase your chances',
      'Partner Country (non-EU) scholarships are more competitive but more generous',
      'Deadlines are typically in January — start preparing months ahead',
    ],
    languageRequirements: ['Varies by programme; usually English at B2/C1 level'],
    applyUrl: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    officialSourceUrl: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    lastVerified: '2026-04-30',
    sourceNotes: 'There are 100+ different EMJMD programmes, each with its own deadline and requirements. The January deadline is typical but not universal.',
    featured: false,
    tags: ['Europe', 'Mobility', 'Joint Degree', 'All Fields'],
    hostCountry: 'Multiple',
    category: 'EU Programme',
    createdAt: '2024-03-01',
  },
];
