import { CompactScholarship } from './scholarship-factory';

const LV = '2026-05-04';

export const GOV_BATCH1: CompactScholarship[] = [
  {
    id: 'gov-1',
    t: 'Chinese Government Scholarship',
    on: 'Chinese Government Scholarship (CSC)',
    u: 'China Scholarship Council / Chinese Universities',
    c: 'China',
    cc: '🇨🇳',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-02-15',
    ide: true,
    desc: 'Chinese Government Scholarship supports international students at Chinese universities through embassy, bilateral, and university routes.',
    el: ['Non-Chinese citizen in good health', 'Meet age limits for the chosen study level', 'Meet admission and language requirements of the applied university'],
    ben: ['Tuition waiver', 'Accommodation or accommodation subsidy', 'Monthly stipend', 'Comprehensive medical insurance'],
    cd: ['Full scholarship package administered through CSC routes', 'Coverage can vary by scholarship type and admitting university'],
    req: ['CSC online application', 'Pre-admission or admission documents when required', 'Academic transcripts and diplomas', 'Language proficiency proof'],
    rdoc: ['Application form', 'Passport copy', 'Diplomas and transcripts', 'Study plan or research proposal', 'Recommendation letters', 'Foreigner physical examination form'],
    ap: ['Check the embassy or university route for your country', 'Apply through the CSC/CampusChina online system', 'Submit required documents by the route deadline', 'Track nomination and admission results'],
    sc: ['Academic record', 'Programme fit', 'Language readiness', 'University or embassy nomination requirements'],
    tips: ['Check the Chinese embassy page for your country because deadlines and document rules vary', 'Secure pre-admission early when your route requires it'],
    lr: ['Chinese-taught programmes require HSK level set by the university or call', 'English-taught programmes require English proficiency proof'],
    ec: ['All countries except listed exclusions'],
    ic: ['China'],
    ecn: 'Official embassy calls state applicants must be citizens of a country other than the People\'s Republic of China; exact route availability and deadlines vary by country or university.',
    esu: 'https://www.campuschina.org/',
    url: 'https://www.campuschina.org/',
    osu: 'https://www.campuschina.org/',
    lv: LV,
    sn: 'Current embassy-route deadlines vary by country; next-cycle date is estimated from recent official embassy calls.',
    feat: true,
    tags: ['China', 'Government', 'CSC', 'All Levels'],
    hc: 'China',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-2',
    t: 'Türkiye Scholarships',
    on: 'Türkiye Scholarships Full-Time Programmes',
    u: 'Presidency for Turks Abroad and Related Communities',
    c: 'Turkey',
    cc: '🇹🇷',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-02-20',
    ide: true,
    desc: 'Türkiye Scholarships combines university placement with Turkish government funding for international full-time degree students.',
    el: ['Citizen of a country other than Turkey', 'Meet academic minimums for the chosen level', 'Meet age limits for associate, bachelor, master, PhD, or research tracks'],
    ben: ['University and department placement', 'Monthly stipend', 'Tuition fee', 'Accommodation', 'Health insurance', 'One-year Turkish language course', 'Once-off flight ticket'],
    cd: ['Full tuition and placement support', 'Monthly stipend by degree level', 'Accommodation, health insurance, Turkish course, and flight support'],
    req: ['Online TBBS application', 'Academic documents', 'Valid identity document or passport', 'Exam or language scores when requested'],
    rdoc: ['Diploma or graduation certificate', 'Transcript', 'Passport or national ID', 'Statement of purpose', 'Recommendation letters', 'Research proposal for PhD where required'],
    ap: ['Create an account in the Türkiye Scholarships application system', 'Choose eligible programmes', 'Upload required documents', 'Submit before the annual deadline', 'Attend interview if shortlisted'],
    sc: ['Academic achievement', 'Motivation and future goals', 'Programme fit', 'Interview performance'],
    tips: ['Use the official TBBS portal only', 'Explain why your study plan fits Turkey and your home country goals'],
    lr: ['One-year Turkish language course is included', 'Programme language requirements may still apply'],
    ec: ['All countries except listed exclusions'],
    ic: ['Turkey'],
    ecn: 'Official criteria list citizens of all countries as eligible, while Turkish citizens and people who lost Turkish citizenship are ineligible.',
    esu: 'https://www.turkiyeburslari.gov.tr/scholarshipsprograms',
    url: 'https://www.turkiyeburslari.gov.tr/',
    osu: 'https://www.turkiyeburslari.gov.tr/fulltimeprograms',
    lv: LV,
    sn: 'Full-time programme applications are normally received between 10 January and 20 February each year; next-cycle date is estimated.',
    feat: true,
    tags: ['Turkey', 'Government', 'All Levels', 'Full Scholarship'],
    hc: 'Turkey',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-3',
    t: 'Eiffel Excellence Scholarship',
    on: 'France Excellence Eiffel Scholarship Program',
    u: 'French Ministry for Europe and Foreign Affairs / Campus France',
    c: 'France',
    cc: '🇫🇷',
    dl: ['Master', 'PhD'],
    ft: 'Stipend',
    d: '2027-01-08',
    ide: true,
    desc: 'France Excellence Eiffel helps French higher education institutions attract top foreign students for priority master, engineering, and doctoral programmes.',
    el: ['Non-French nationality', 'Submitted by a French higher education institution', 'Master applicants within the age limit', 'PhD applicants within the age limit'],
    ben: ['Monthly allowance', 'International and national transport support', 'Insurance', 'Housing search assistance', 'Cultural activities'],
    cd: ['Monthly allowance for master or doctoral level', 'Travel, insurance, housing assistance, and cultural activity support', 'Tuition fees are not covered by Eiffel'],
    req: ['Nomination by French institution', 'Academic record', 'Study or research project', 'Institutional application documents'],
    rdoc: ['Institution nomination dossier', 'CV', 'Transcripts', 'Programme description', 'Research project for PhD candidates'],
    ap: ['Contact Campus France, a French embassy, or the target institution', 'Apply through the French institution process', 'Institution submits the Eiffel nomination to Campus France', 'Wait for Campus France results'],
    sc: ['Academic excellence', 'Priority field fit', 'Quality of project', 'Institutional strategy and nomination strength'],
    tips: ['Students cannot apply directly to Campus France', 'Contact French institutions months before the Campus France deadline'],
    lr: ['French or English requirements depend on the host programme'],
    ec: ['All countries except listed exclusions'],
    ic: ['France'],
    ecn: 'Official source frames Eiffel as a programme for foreign students; candidates with French nationality are not eligible under the programme rules.',
    esu: 'https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program',
    url: 'https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program',
    osu: 'https://www.campusfrance.org/en/the-france-excellence-eiffel-scholarship-program',
    lv: LV,
    sn: 'The 2026 Campus France institutional deadline was 8 January 2026; next-cycle date is estimated until the 2027 call is published.',
    tags: ['France', 'Government', 'Excellence', 'Campus France'],
    hc: 'France',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-4',
    t: 'New Zealand Manaaki Scholarships',
    on: 'Manaaki New Zealand Scholarships Programme',
    u: 'Education New Zealand / New Zealand Government',
    c: 'New Zealand',
    cc: '🇳🇿',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-04-10',
    ide: true,
    desc: 'Manaaki New Zealand Scholarships support citizens from eligible partner countries to study development-relevant qualifications in New Zealand or, for some Pacific countries, at Pacific universities.',
    el: ['Citizen of an eligible partner country', 'Meet country-specific study level and subject rules', 'Meet citizenship, work experience, and return-home requirements'],
    ben: ['Full tuition fees', 'Living allowance', 'Establishment allowance', 'Medical insurance', 'Travel to and from home country', 'Research and thesis support where applicable'],
    cd: ['Fully funded study package for eligible qualifications', 'Country-specific study levels and priority subjects apply'],
    req: ['Online eligibility check', 'Academic records', 'Proof of citizenship', 'English evidence when required', 'Work experience evidence where required'],
    rdoc: ['Passport or citizenship proof', 'Academic transcripts', 'Qualification certificates', 'English test evidence if requested', 'Employer or work history documents where required'],
    ap: ['Check eligible countries and country-specific requirements', 'Complete the online eligibility test', 'Submit online application during your country window', 'Follow selection and preferred-candidate steps'],
    sc: ['Development impact fit', 'Academic readiness', 'Leadership and community contribution', 'Alignment with country priority subjects'],
    tips: ['Apply early because the portal may close early for high-volume countries', 'Match your study plan to your country priorities'],
    lr: ['English requirements depend on institution and qualification'],
    ec: ['Fiji', 'French Polynesia', 'Kiribati', 'Nauru', 'New Caledonia', 'Niue', 'Federated States of Micronesia', 'Palau', 'Marshall Islands', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu', 'Wallis and Futuna', 'Cambodia', 'Indonesia', 'Lao PDR', 'Malaysia', 'Nepal', 'Philippines', 'Thailand', 'Timor-Leste', 'Viet Nam'],
    ic: [],
    ecn: 'Official Manaaki page lists eligible Pacific and Asian countries; study levels and application rules vary by country and some Pacific options are restricted.',
    esu: 'https://www.nzscholarships.govt.nz/check-eligible-countries',
    url: 'https://www.nzscholarships.govt.nz/',
    osu: 'https://www.nzscholarships.govt.nz/how-to-apply-for-a-scholarship/',
    lv: LV,
    sn: 'The 2026 application round has closed; next-cycle deadline is estimated from recent official windows and may vary by country.',
    tags: ['New Zealand', 'Government', 'Development', 'Manaaki'],
    hc: 'New Zealand',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-5',
    t: 'Swiss Government Excellence Scholarships',
    on: 'Swiss Government Excellence Scholarships for Foreign Scholars and Artists',
    u: 'Swiss Confederation / SERI / FCS',
    c: 'Switzerland',
    cc: '🇨🇭',
    dl: ['PhD', 'Postdoc'],
    ft: 'Stipend',
    d: '2026-12-01',
    ide: true,
    desc: 'Swiss Government Excellence Scholarships support early-career foreign researchers and, for selected countries, artists through country-specific calls managed by Swiss representations.',
    el: ['Foreign early-career researcher or eligible artist', 'Master or PhD background depending on scholarship type', 'Academic supervisor support in Switzerland for research tracks', 'Meet country-specific call rules'],
    ben: ['Monthly scholarship amount', 'Health insurance support for eligible non-EU/EFTA recipients', 'Housing allowance where provided', 'Swiss research or art study opportunity'],
    cd: ['Research, PhD, postdoctoral, or art scholarship depending on country', 'Amounts and available types are set in official FCS documents'],
    req: ['Country-specific application package', 'Research proposal or art portfolio', 'Swiss supervisor letter for research tracks', 'Academic transcripts and references'],
    rdoc: ['Signed FCS application form', 'CV', 'Motivation letter', 'Research proposal or portfolio', 'Supervisor support letter', 'Academic certificates', 'Recommendation letters'],
    ap: ['Open the official country A-Z list', 'Download the country-specific call package', 'Prepare supervisor-backed application', 'Submit through the Swiss representation for your country'],
    sc: ['Candidate profile', 'Quality of research project or artistic work', 'Supervisor support and cooperation potential'],
    tips: ['Never pay fees for Swiss Government scholarship offers', 'Start supervisor outreach before the country deadline'],
    lr: ['Language requirements depend on the Swiss host institution and project'],
    ec: ['Countries with Swiss Government Excellence Scholarship calls'],
    ic: [],
    ecn: 'Official SERI source states the 2026-2027 programme is open to applicants from 183 countries, with scholarship type and deadline depending on country of origin.',
    esu: 'https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships',
    url: 'https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships',
    osu: 'https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships-at-a-glance',
    lv: LV,
    sn: 'Application deadlines are country-specific; date shown is a conservative estimated placeholder for display.',
    tags: ['Switzerland', 'Government', 'Research', 'SERI'],
    hc: 'Switzerland',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-6',
    t: 'Italian Government MAECI Scholarships',
    on: 'MAECI Grants for Foreign Students and Italian Citizens Residing Abroad',
    u: 'Italian Ministry of Foreign Affairs and International Cooperation',
    c: 'Italy',
    cc: '🇮🇹',
    dl: ['Master', 'PhD'],
    ft: 'Stipend',
    d: '2027-03-26',
    ide: true,
    desc: 'The Italian Government offers MAECI grants for foreign students and Italian citizens residing abroad to attend eligible study, training, or research programmes in Italy.',
    el: ['Foreign student or Italian citizen residing abroad', 'Citizen/resident status covered by the annual eligible countries list', 'Meet age, academic, and programme requirements in the annual call'],
    ben: ['Financial grant', 'Health and accident insurance coverage', 'Support for eligible study or research in Italy'],
    cd: ['Scholarship duration varies by programme type', 'Grant supports courses held on Italian territory only'],
    req: ['Study in Italy online application', 'Eligible country or territory status', 'Academic documents', 'Language proof where required'],
    rdoc: ['Passport or ID', 'Academic qualifications', 'Transcript', 'CV', 'Admission or research documentation where required', 'Language certificate when required'],
    ap: ['Check the annual call and eligible countries list', 'Register on the Study in Italy portal', 'Complete the online application', 'Submit before the MAECI deadline'],
    sc: ['Academic merit', 'Programme eligibility', 'Language readiness', 'Embassy or commission evaluation where applicable'],
    tips: ['Use only the Study in Italy portal', 'Check your embassy notice and annual call before applying'],
    lr: ['Italian or English language requirements depend on the chosen programme and annual call'],
    ec: ['Eligible countries and territories listed by MAECI'],
    ic: [],
    ecn: 'Official MAECI source publishes the annual call and eligible countries/territories list through Study in Italy; applicants must confirm their country in that list.',
    esu: 'https://studyinitaly.esteri.it/ListaBandi',
    url: 'https://studyinitaly.esteri.it/',
    osu: 'https://studyinitaly.esteri.it/ListaBandi',
    lv: LV,
    sn: 'The 2026-2027 deadline was 26 March 2026; next-cycle deadline is estimated until MAECI publishes the next call.',
    tags: ['Italy', 'Government', 'MAECI', 'Study in Italy'],
    hc: 'Italy',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-7',
    t: 'Government of Ireland International Education Scholarships',
    on: 'Government of Ireland International Education Scholarship (GOI-IES)',
    u: 'Higher Education Authority / Government of Ireland',
    c: 'Ireland',
    cc: '🇮🇪',
    dl: ['Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-03-12',
    ide: true,
    desc: 'GOI-IES supports high-calibre international students for one year of full-time study at NFQ level 9 or 10 in eligible Irish higher education institutions.',
    el: ['Domiciliary of origin outside the EU/EEA, Switzerland, and the United Kingdom', 'Conditional or final offer from an eligible Irish higher education institution', 'Programme at NFQ level 9 or 10'],
    ben: ['EUR 10,000 stipend for one year', 'Full fee waiver from the host institution'],
    cd: ['One year of full-time master, postgraduate diploma, or PhD study', '60 scholarships awarded annually'],
    req: ['Offer from eligible Irish HEI', 'GOI-IES application', 'Academic and extracurricular evidence', 'Study rationale for Ireland'],
    rdoc: ['Admission offer', 'Academic transcripts', 'Application statements', 'Evidence of achievements and activities', 'References if requested by the call'],
    ap: ['Apply to an eligible Irish HEI first', 'Secure a conditional or final offer', 'Submit GOI-IES application through the portal', 'HEI checks eligibility and shortlists applications'],
    sc: ['Academic achievement', 'Communication skills', 'Extracurricular activity', 'Rationale for studying in Ireland', 'Alignment with institution strategy'],
    tips: ['Apply to the Irish institution early because an offer is required before scholarship application', 'Use concrete examples in the study-in-Ireland rationale'],
    lr: ['English language requirements are set by the Irish host institution'],
    ec: ['All countries except listed exclusions'],
    ic: ['EU/EEA countries', 'Switzerland', 'United Kingdom'],
    ecn: 'Official HEA source requires domiciliary of origin outside the EU/EEA, Switzerland, and the United Kingdom.',
    esu: 'https://hea.ie/policy/internationalisation/goi-ies/',
    url: 'https://hea.ie/policy/internationalisation/goi-ies/',
    osu: 'https://hea.ie/policy/internationalisation/goi-ies/',
    lv: LV,
    sn: 'The 2026 call closed on 12 March 2026; next-cycle deadline is estimated until HEA publishes the next call.',
    tags: ['Ireland', 'Government', 'GOI-IES', 'Postgraduate'],
    hc: 'Ireland',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-8',
    t: 'Stipendium Hungaricum',
    on: 'Stipendium Hungaricum Scholarship Programme',
    u: 'Tempus Public Foundation / Government of Hungary',
    c: 'Hungary',
    cc: '🇭🇺',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-01-15',
    ide: true,
    desc: 'Stipendium Hungaricum is Hungary\'s government scholarship programme for students nominated by official Sending Partners to study at Hungarian higher education institutions.',
    el: ['Citizen of a Sending Partner country or territory', 'Nominated by the responsible Sending Partner', 'Apply to eligible Hungarian programmes', 'Meet host institution admission requirements'],
    ben: ['Tuition-free education', 'Monthly stipend', 'Dormitory placement or accommodation contribution', 'Medical insurance support'],
    cd: ['Full tuition waiver', 'Monthly support by study level', 'Accommodation and medical insurance support according to programme rules'],
    req: ['Online application', 'Sending Partner nomination', 'Academic documents', 'Motivation letter', 'Medical certificate if requested'],
    rdoc: ['Application form', 'Motivation letter', 'Proof of language proficiency', 'School certificates and transcripts', 'Passport', 'Medical certificate where required'],
    ap: ['Confirm your Sending Partner and eligible study fields', 'Submit online application by Tempus deadline', 'Complete Sending Partner nomination process', 'Pass host institution entrance exams'],
    sc: ['Sending Partner nomination', 'Academic record', 'Entrance exam score', 'Programme fit'],
    tips: ['Check both Tempus and Sending Partner deadlines', 'Choose only programmes allowed for your country agreement'],
    lr: ['Language requirement depends on the selected Hungarian programme'],
    ec: ['Stipendium Hungaricum Sending Partner countries and territories'],
    ic: [],
    ecn: 'Official partner page lists eligible Sending Partners and country-specific fields, contacts, and nomination procedures.',
    esu: 'https://stipendiumhungaricum.hu/partners/',
    url: 'https://stipendiumhungaricum.hu/apply/',
    osu: 'https://stipendiumhungaricum.hu/apply/',
    lv: LV,
    sn: 'The 2026-2027 application deadline was 15 January 2026; next-cycle deadline is estimated from the annual call pattern.',
    tags: ['Hungary', 'Government', 'Sending Partner', 'All Levels'],
    hc: 'Hungary',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-9',
    t: 'Polish NAWA Scholarships',
    on: 'Stefan Banach NAWA Scholarship Programme',
    u: 'Polish National Agency for Academic Exchange / Ministry of Foreign Affairs',
    c: 'Poland',
    cc: '🇵🇱',
    dl: ['Master'],
    ft: 'Stipend',
    d: '2026-05-08',
    ide: true,
    desc: 'The Stefan Banach NAWA Programme supports citizens of Polish Aid partner countries to pursue full-time second-cycle studies in Poland.',
    el: ['Citizen of an eligible Polish Aid country', 'No Polish citizenship', 'Bachelor degree obtained no earlier than 2024 or by 15 July 2026', 'No master degree already held', 'Language proficiency for the chosen study path'],
    ben: ['Monthly scholarship of PLN 2,500', 'Tuition fee exemption at public universities', 'Preparatory Polish course for Polish-track students', 'Travel allowance'],
    cd: ['Second-cycle master study support', 'Polish or English study path', 'One-time travel allowance and public-university tuition waiver'],
    req: ['NAWA online application', 'Bachelor diploma or graduation evidence', 'Language proficiency proof', 'Self-presentation video'],
    rdoc: ['Passport', 'Bachelor diploma or confirmation', 'Transcript', 'Language certificate', 'Application statements', 'Self-presentation video'],
    ap: ['Check the official Banach call and eligible countries', 'Prepare language and academic documents', 'Submit through the NAWA system', 'Apply separately for admission to a Polish university'],
    sc: ['Formal eligibility', 'Academic performance', 'Motivation', 'Development impact and programme fit'],
    tips: ['Submit early because NAWA may close once application limits are reached', 'Remember NAWA scholarship application and university admission are separate'],
    lr: ['English B2 for English-language studies', 'Polish B2 or B1 depending on Polish-language path'],
    ec: ['Albania', 'Angola', 'Argentina', 'Armenia', 'Azerbaijan', 'Belarus', 'Bosnia and Herzegovina', 'Brazil', 'Georgia', 'India', 'Indonesia', 'Iraq', 'Iran', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo', 'Lebanon', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Nigeria', 'North Macedonia', 'Palestine', 'Papua New Guinea', 'Peru', 'Philippines', 'Rwanda', 'Senegal', 'Serbia', 'Tanzania', 'Tunisia', 'Ukraine', 'Uzbekistan', 'Vietnam'],
    ic: ['Poland'],
    ecn: 'Official NAWA applicant information lists 36 eligible countries and requires applicants not to hold Polish citizenship.',
    esu: 'https://nawa.gov.pl/en/nawa/news/call-for-applications-banach-nawa-2026',
    url: 'https://nawa.gov.pl/en/nawa/news/call-for-applications-banach-nawa-2026',
    osu: 'https://nawa.gov.pl/en/nawa/news/call-for-applications-banach-nawa-2026',
    lv: LV,
    sn: 'Current 2026 call deadline is 8 May 2026, 3:00 p.m. CEST, or earlier if application limits are reached.',
    tags: ['Poland', 'Government', 'NAWA', 'Banach'],
    hc: 'Poland',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov-10',
    t: 'Romanian Government Scholarship',
    on: 'Ministry of Foreign Affairs Scholarships for Non-EU Citizens',
    u: 'Romanian Ministry of Foreign Affairs / Study in Romania',
    c: 'Romania',
    cc: '🇷🇴',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-03-31',
    ide: true,
    desc: 'The Romanian Government offers annual MFA scholarships for non-EU citizens to study at accredited Romanian higher education institutions.',
    el: ['Foreign citizen from a non-EU country', 'Good academic results', 'Not covered by listed ineligible categories', 'Choose eligible fields outside Medicine, Dental Medicine, and Pharmacy'],
    ben: ['Tuition fee coverage', 'Monthly scholarship support', 'Preparatory Romanian language year where required', 'Accommodation support according to Romanian rules'],
    cd: ['Bachelor and master studies are generally in Romanian with preparatory year support', 'PhD may be in Romanian, English, or another language set by the doctoral school'],
    req: ['Online application through Study in Romania platform', 'Academic average meeting programme requirements', 'Eligible field and cycle', 'Complete document file'],
    rdoc: ['Diplomas', 'Transcripts', 'Birth certificate', 'Passport pages', 'CV', 'Doctoral letter of intent and tutor agreement where applicable'],
    ap: ['Create an account on the official Study in Romania scholarship platform', 'Complete the online application', 'Upload required documents', 'Submit before the MFA deadline', 'Wait for selection results'],
    sc: ['Academic results', 'Completeness of file', 'Programme fit', 'Ministry selection rules'],
    tips: ['Do not apply through third-party agents', 'Check excluded fields and language rules before choosing programmes'],
    lr: ['Romanian preparatory year is granted for non-Romanian speakers', 'PhD may allow English or another doctoral-school language'],
    ec: ['All countries except listed exclusions'],
    ic: ['EU countries'],
    ecn: 'Official Study in Romania source states the MFA scholarship is for foreign citizens from all non-EU countries, with additional excluded applicant categories listed in the programme rules.',
    esu: 'https://scholarships.studyinromania.gov.ro/scholarship-about',
    url: 'https://scholarships.studyinromania.gov.ro/',
    osu: 'https://studyinromania.gov.ro/mfa_2026-2027',
    lv: LV,
    sn: 'The 2026 application period was 16 February to 31 March 2026; next-cycle deadline is estimated until the 2027 call is published.',
    tags: ['Romania', 'Government', 'Non-EU', 'All Levels'],
    hc: 'Romania',
    cat: 'Government',
    ca: '2026-05-04',
  },
];
