import { Scholarship } from '@/types';

/** Scholarships 7-12 fully source-backed */
export const ORIGINAL_12_B: Scholarship[] = [
  {
    id: '7',
    title: 'Gates Cambridge Scholarship',
    officialName: 'Gates Cambridge Scholarships',
    university: 'University of Cambridge',
    country: 'United Kingdom',
    countryCode: '🇬🇧',
    degreeLevel: ['Master', 'PhD'],
    fundingType: 'Fully Funded',
    deadline: '2026-10-12',
    isDeadlineEstimated: true,
    description: 'Gates Cambridge Scholarships are awarded to outstanding applicants from outside the UK to pursue a full-time postgraduate degree at the University of Cambridge. Funded by the Bill and Melinda Gates Foundation.',
    eligibility: [
      'Citizen of any country outside the United Kingdom',
      'Applying for a full-time residential postgraduate degree at Cambridge (PhD, MLitt, one-year Master\'s, or MPhil)',
      'Outstanding intellectual ability',
      'Commitment to improving the lives of others',
    ],
    benefits: ['Full cost of study at Cambridge', 'Maintenance allowance (currently £21,000 for 12 months)', 'One economy single airfare at the start and end of the course', 'Inbound visa costs and Immigration Health Surcharge'],
    coverageDetails: ['Full tuition (University Composition Fee and College fees)', 'Annual maintenance allowance', 'Economy return airfare', 'Visa and health surcharge costs'],
    requirements: [],
    requiredDocuments: ['Cambridge graduate admissions application', 'Gates Cambridge scholarship statement (part of the Cambridge application)', 'Academic transcripts', 'Two academic references', 'Research proposal (for PhD applicants)', 'CV'],
    applicationProcess: ['Submit the Cambridge graduate application by the relevant funding deadline', 'The Gates Cambridge statement is integrated into the Cambridge application — no separate application', 'Departments and faculties shortlist candidates', 'Shortlisted candidates are interviewed by Gates Cambridge committees', 'Decisions communicated by late March/April'],
    selectionCriteria: ['Outstanding intellectual ability', 'Reasons for choice of course', 'A commitment to improving the lives of others', 'Leadership potential'],
    applicationTips: ['Apply by the earliest Cambridge funding deadline (usually October for US; December for non-US)', 'The Gates Cambridge statement is critical — clearly explain how your work will improve others\' lives', 'PhD applicants should have a well-defined research proposal with supervisor support', 'Demonstrating leadership through action, not just titles, is valued'],
    languageRequirements: ['Meet the University of Cambridge\'s English language requirements for your programme'],
    applyUrl: 'https://www.gatescambridge.org/',
    officialSourceUrl: 'https://www.gatescambridge.org/apply/',
    lastVerified: '2026-04-30',
    sourceNotes: 'US-resident applicants have an earlier deadline (typically October). All other applicants apply by the December Cambridge deadline.',
    featured: true,
    tags: ['Cambridge', 'UK', 'Research', 'Leadership'],
    hostCountry: 'United Kingdom',
    category: 'University',
    createdAt: '2024-03-10',
  },
  {
    id: '8',
    title: 'Swedish Institute Scholarships',
    officialName: 'Swedish Institute Scholarships for Global Professionals (SISGP)',
    university: 'Various Swedish Universities',
    country: 'Sweden',
    countryCode: '🇸🇪',
    degreeLevel: ['Master'],
    fundingType: 'Fully Funded',
    deadline: '2026-02-10',
    isDeadlineEstimated: true,
    description: 'The Swedish Institute Study Scholarships target future leaders from eligible countries who wish to pursue a master\'s degree in Sweden. The programme aims to develop global leaders who contribute to the UN Sustainable Development Goals.',
    eligibility: [
      'Citizen of an eligible country (list published by Swedish Institute)',
      'Applied to and been granted admission to an eligible master\'s programme in Sweden',
      'Demonstrate work/voluntary experience of at least 3,000 hours',
      'Demonstrate leadership and sustainability engagement',
    ],
    benefits: ['Monthly living allowance of SEK 11,000', 'Tuition fee coverage paid directly to the university', 'Travel grant for one trip to Sweden and one return trip', 'Insurance', 'Membership in the SI Network for Future Global Leaders'],
    coverageDetails: ['SEK 11,000/month living allowance', 'Full tuition fee coverage', 'Travel grant', 'Insurance coverage', 'SI Network membership'],
    requirements: [],
    requiredDocuments: ['Swedish university application through universityadmissions.se', 'Separate SI scholarship application through the SI online portal', 'CV documenting 3,000+ hours of work/voluntary experience', 'Motivation letter focusing on leadership and sustainability', 'Documentation of work experience'],
    applicationProcess: ['Apply to master\'s programmes in Sweden through universityadmissions.se (deadline January)', 'Submit a separate scholarship application on the SI website (deadline typically February)', 'SI evaluates applications and announces results in April', 'Admitted and awarded students confirm acceptance'],
    selectionCriteria: ['Leadership experience and potential', 'Professional and academic background', 'Engagement with sustainability and the SDGs', 'Action plan for using the degree after returning home'],
    applicationTips: ['You must apply to the university AND the SI scholarship separately — they are independent', 'Emphasize concrete leadership actions, not just positions held', 'Link your motivation clearly to the Sustainable Development Goals', 'The 3,000-hour work experience requirement is strict — document it carefully'],
    languageRequirements: ['IELTS 6.5 or TOEFL 90 required by most Swedish master\'s programmes'],
    applyUrl: 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/',
    officialSourceUrl: 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/',
    lastVerified: '2026-04-30',
    sourceNotes: 'SI scholarship application opens after the university application deadline. Both are required.',
    featured: false,
    tags: ['Sweden', 'Leadership', 'Sustainability', 'Postgraduate'],
    hostCountry: 'Sweden',
    category: 'Government',
    createdAt: '2024-03-15',
  },
  {
    id: '9',
    title: 'Rhodes Scholarship',
    officialName: 'The Rhodes Scholarships',
    university: 'University of Oxford',
    country: 'United Kingdom',
    countryCode: '🇬🇧',
    degreeLevel: ['Master', 'PhD'],
    fundingType: 'Fully Funded',
    deadline: '2026-08-01',
    isDeadlineEstimated: true,
    description: 'The Rhodes Scholarship is the oldest and most celebrated international fellowship. Rhodes Scholars are selected on the basis of intellect, character, leadership, and commitment to service, and study at the University of Oxford.',
    eligibility: [
      'Citizen of an eligible country (Rhodes constituencies worldwide)',
      'Age 19 to 25 at the time of entry (some constituencies allow up to 28)',
      'Completed or on track to complete an undergraduate degree by the start of the scholarship',
      'Outstanding academic achievement',
    ],
    benefits: ['All university and college fees', 'Annual personal stipend (sufficient for living costs in Oxford)', 'Economy class airfare to and from Oxford', 'Settling-in allowance', 'Research and conference travel grants'],
    coverageDetails: ['Full university and college fees', 'Annual personal stipend', 'Economy return airfare', 'Settling-in allowance', 'Travel grants for research'],
    requirements: [],
    requiredDocuments: ['Online application through the Rhodes Trust portal', 'Personal statement', 'Academic transcripts', 'Five letters of recommendation (four academic, one personal)', 'Passport/ID confirmation', 'Research proposal (for DPhil applicants)'],
    applicationProcess: ['Apply through your country\'s Rhodes constituency by the local deadline (typically July–October)', 'Selected applicants are invited to in-person interviews by a national selection committee', 'Finalists attend a selection dinner and interview weekend', 'Successful candidates are announced by November/December'],
    selectionCriteria: ['Literary and scholastic attainments', 'Energy to use one\'s talents to the full', 'Truth, courage, devotion to duty, sympathy for others', 'Moral force of character and leadership'],
    applicationTips: ['Each country has its own deadline — check rhodeshouse.ox.ac.uk for your constituency', 'Five strong referees who know you well are essential — start asking early', 'Show genuine commitment to service and public good, not just academic achievement', 'Prepare for the interview by thinking deeply about your values and how you act on them'],
    applyUrl: 'https://www.rhodeshouse.ox.ac.uk/scholarships/apply/',
    officialSourceUrl: 'https://www.rhodeshouse.ox.ac.uk/scholarships/apply/',
    lastVerified: '2026-04-30',
    sourceNotes: 'Deadlines vary by country. US deadline is typically early October. Check your constituency page.',
    featured: false,
    tags: ['Oxford', 'Leadership', 'Prestigious', 'UK'],
    hostCountry: 'United Kingdom',
    category: 'University',
    createdAt: '2024-04-01',
  },
  {
    id: '10',
    title: 'Global Korea Scholarship (GKS)',
    officialName: 'Korean Government Scholarship Program (KGSP / GKS)',
    university: 'Various Korean Universities',
    country: 'South Korea',
    countryCode: '🇰🇷',
    degreeLevel: ['Bachelor', 'Master', 'PhD'],
    fundingType: 'Fully Funded',
    deadline: '2026-03-01',
    isDeadlineEstimated: true,
    description: 'The Global Korea Scholarship (formerly KGSP) is provided by the Korean Government to international students to study at Korean universities. It covers undergraduate and graduate studies with full financial support including Korean language training.',
    eligibility: [
      'Citizen of a country that has diplomatic relations with South Korea',
      'Under 25 years old (undergraduate) or under 40 (graduate) at the time of entry',
      'GPA of 80% or above (on a 100-point scale)',
      'Good health, both physically and mentally',
      'Not a Korean national or dual citizen with Korean nationality',
    ],
    benefits: ['Full tuition fees', 'Monthly allowance of KRW 900,000 (graduate) or KRW 800,000 (undergraduate)', 'Round-trip airfare', 'Medical insurance', 'Korean language training for one year', 'Settlement allowance', 'Completion grant'],
    coverageDetails: ['Full tuition', 'Monthly allowance KRW 800,000–900,000', 'Round-trip airfare', 'Medical insurance', 'One year Korean language training', 'Settlement and completion allowances'],
    requirements: [],
    requiredDocuments: ['GKS application form', 'Personal statement and study plan', 'Two recommendation letters', 'Academic transcripts and degree certificates', 'Proof of citizenship (applicant and parents)', 'Medical health certificate', 'Korean or English language proficiency certificate'],
    applicationProcess: ['Apply through the Korean Embassy in your country (Embassy Track) OR through a Korean university (University Track)', 'Submit documents to the relevant embassy or university by their deadline', 'First screening: document evaluation', 'Second screening: interview (Embassy Track)', 'Final selection by the National Institute for International Education (NIIED)'],
    selectionCriteria: ['Academic performance (GPA)', 'Study plan quality', 'Korean or English language ability', 'Recommendation letters', 'Interview performance (Embassy Track)'],
    applicationTips: ['There are two tracks: Embassy Track and University Track — you can apply to one', 'The Embassy Track typically has a deadline around February–March', 'Korean language ability is not required at application but learning basics helps', 'Prepare a specific study plan tied to a Korean university and department'],
    languageRequirements: ['Korean TOPIK Level 3+ or English proficiency test (TOEFL/IELTS) depending on the programme language', 'One year of Korean language training is provided before degree studies begin'],
    applyUrl: 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do',
    officialSourceUrl: 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do',
    lastVerified: '2026-04-30',
    sourceNotes: 'Application timelines differ between Embassy Track and University Track. Check studyinkorea.go.kr for current dates.',
    featured: false,
    tags: ['South Korea', 'Asia', 'All Levels', 'Government'],
    hostCountry: 'South Korea',
    category: 'Government',
    createdAt: '2024-04-10',
  },
  {
    id: '11',
    title: 'Aga Khan Foundation International Scholarship Programme',
    officialName: 'Aga Khan Foundation International Scholarship Programme',
    university: 'Various Universities Worldwide',
    country: 'Multiple',
    countryCode: '🌍',
    degreeLevel: ['Master'],
    fundingType: 'Fully Funded',
    deadline: '2026-03-31',
    isDeadlineEstimated: true,
    description: 'The Aga Khan Foundation provides a limited number of scholarships each year for postgraduate studies to outstanding students from select developing countries who have no other means of financing their studies. Scholarships are awarded as 50% grant and 50% loan.',
    eligibility: [
      'Citizen of a country where AKF has an active programme (listed on akdn.org)',
      'Pursuing a master\'s degree relevant to development',
      'Committed to returning to home country or AKF-operating country after studies',
      'Demonstrated financial need — no other means to finance studies',
      'Have already applied to or been admitted to a university programme',
    ],
    benefits: ['Tuition fees (50% grant, 50% interest-free loan)', 'Living stipend (50% grant, 50% interest-free loan)', 'Travel costs may be covered in some cases'],
    coverageDetails: ['Tuition support (50% grant, 50% loan)', 'Living costs support (50% grant, 50% loan)', 'Travel costs (case by case)'],
    requirements: [],
    requiredDocuments: ['AKF application form (from local AKF office or AKDN website)', 'Proof of university admission or pending application', 'Academic transcripts', 'Financial need documentation', 'Letters of recommendation', 'Evidence of community involvement'],
    applicationProcess: ['Contact the AKF office in your country of citizenship', 'Obtain and complete the application form', 'Submit supporting documents including financial need evidence', 'Applications are reviewed nationally, then internationally', 'Decisions are communicated several months after the deadline'],
    selectionCriteria: ['Academic excellence', 'Genuine financial need', 'Relevance of study to development goals', 'Commitment to community service and return to home region'],
    applicationTips: ['Start by contacting your local AKF office — the process begins there', 'Financial need must be clearly documented — provide bank statements, family income proof', 'Community service and volunteerism strengthen your application significantly', 'The loan portion is interest-free and repayable after you begin working — factor this in'],
    applyUrl: 'https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarship-programme',
    officialSourceUrl: 'https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarship-programme',
    lastVerified: '2026-04-30',
    sourceNotes: 'Half grant, half interest-free loan. Application timelines and forms vary by country. Contact your local AKF office.',
    featured: false,
    tags: ['Development', 'Need-Based', 'Global', 'Service'],
    hostCountry: 'Multiple',
    category: 'Foundation',
    createdAt: '2024-04-15',
  },
  {
    id: '12',
    title: 'MEXT Scholarship',
    officialName: 'Japanese Government (MEXT) Scholarship',
    university: 'Various Japanese Universities',
    country: 'Japan',
    countryCode: '🇯🇵',
    degreeLevel: ['Bachelor', 'Master', 'PhD'],
    fundingType: 'Fully Funded',
    deadline: '2026-05-15',
    isDeadlineEstimated: true,
    description: 'The Japanese Government (Monbukagakusho/MEXT) Scholarship is one of the most comprehensive government scholarships in the world. It supports international students to study at Japanese universities through Embassy Recommendation and University Recommendation routes.',
    eligibility: [
      'Citizen of a country with diplomatic relations with Japan',
      'Age requirements vary by programme type',
      'Meet academic requirements for the desired programme level',
      'Good physical and mental health',
      'Willing to learn Japanese (or study in English where available)',
    ],
    benefits: ['Full tuition exemption and admission fee waiver', 'Monthly stipend of approximately ¥143,000–¥148,000 (graduate)', 'Round-trip economy class airfare', 'Japanese language preparatory training (6 months to 1 year)'],
    coverageDetails: ['Full tuition and admission fee waiver', 'Monthly stipend ¥143,000–¥148,000 (graduate level)', 'Round-trip economy airfare', 'Japanese language training (up to 1 year)'],
    requirements: [],
    requiredDocuments: ['MEXT application form', 'Academic transcripts and degree certificates', 'Research plan or study plan', 'Medical certificate', 'Recommendation from current/previous university', 'Passport copy', 'Japanese or English language proficiency evidence'],
    applicationProcess: [
      'Embassy Recommendation: Apply at the Japanese Embassy/Consulate in your country (April–June)',
      'Embassy conducts written exams (Japanese, English, and subject tests) and interviews',
      'University Recommendation: Contact a Japanese university directly to be nominated',
      'University submits nomination to MEXT',
      'Both routes: Final selection by MEXT in Tokyo',
    ],
    selectionCriteria: ['Academic performance and research potential', 'Quality of research/study plan', 'Japanese or English language ability', 'Interview and exam performance (Embassy route)', 'Professor and university endorsement (University route)'],
    applicationTips: [
      'Two routes exist: Embassy Recommendation and University Recommendation — choose based on your situation',
      'For the University route, contact Japanese professors directly with a clear research proposal',
      'The Embassy route includes written exams — prepare well for subject and language tests',
      'A Letter of Acceptance from a Japanese professor greatly strengthens the University route application',
      'Start early — the Embassy route deadline is typically April–May',
    ],
    languageRequirements: [
      'Japanese language training provided for most programmes',
      'English-taught programmes available at select universities',
      'JLPT N2 or equivalent helps for Japanese-taught programmes',
    ],
    applyUrl: 'https://www.mext.go.jp/en/policy/education/highered/title02/detail02/sdetail02/1373897.htm',
    officialSourceUrl: 'https://www.studyinjapan.go.jp/en/planning/scholarship/application/',
    lastVerified: '2026-04-30',
    sourceNotes: 'Embassy Recommendation deadlines vary by country (typically April–June). University Recommendation deadlines vary by university.',
    featured: false,
    tags: ['Japan', 'Asia', 'Research', 'All Levels', 'STEM'],
    hostCountry: 'Japan',
    category: 'Government',
    createdAt: '2024-04-20',
  },
];
