import { CompactScholarship } from './scholarship-factory';

const E = ['Academic transcripts','Letters of recommendation','Language proficiency certificate'];
const R = ['Online application form','CV/Resume','Personal statement'];

export const BATCH3: CompactScholarship[] = [
{id:'46',t:'Adelaide Scholarships International',u:'University of Adelaide',c:'Australia',cc:'🇦🇺',dl:['Master','PhD'],ft:'Fully Funded',d:'2026-08-31',desc:'ASI provides scholarships for international postgraduate research students at the University of Adelaide, a Group of Eight university.',el:['International student','Accepted into research degree','First-class honours or equivalent'],ben:['Full tuition','Annual living allowance (AUD $35,000+)','OSHC','Relocation allowance'],req:['Research application','Academic transcripts','Research proposal','2 referees'],url:'https://scholarships.adelaide.edu.au/',tags:['Australia','Research','STEM'],hc:'Australia',cat:'University',ca:'2024-10-15'},
{id:'47',t:'Reach Oxford Scholarship',u:'University of Oxford',c:'United Kingdom',cc:'🇬🇧',dl:['Bachelor'],ft:'Fully Funded',d:'2026-10-15',desc:'Reach Oxford covers all costs for students from low-income countries who could not otherwise afford to study at Oxford.',el:['Outstanding academic ability','From a low-income country','Genuine financial need','Apply to Oxford undergraduate'],ben:['Full university and college fees','Living costs grant','Return airfare annually'],req:['Oxford undergraduate application (UCAS)','Financial documentation','Academic records'],url:'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford/',tags:['Oxford','UK','Undergraduate','Need-Based'],hc:'United Kingdom',cat:'University',ca:'2024-10-20'},
{id:'48',t:'Korea Foundation for Advanced Studies (KFAS) Scholarship',u:'Various Universities Worldwide',c:'South Korea',cc:'🇰🇷',dl:['Master','PhD'],ft:'Fully Funded',d:'2026-02-28',desc:'KFAS supports outstanding international students pursuing graduate studies at top universities worldwide, not limited to Korea.',el:['Under 30 (Master), 35 (PhD)','Exceptional academic record','Admitted to a top university globally','Leadership potential'],ben:['Full tuition','Monthly stipend','Research support','Conference travel','Book allowance'],req:['Online application','Academic records','Research proposal','3 references','Interview'],url:'https://www.kfas.or.kr/',tags:['South Korea','Global','Research','All Fields'],hc:'Multiple',cat:'Foundation',ca:'2024-10-25'},
{id:'49',t:'Politecnico di Milano Merit-Based Scholarships',u:'Politecnico di Milano',c:'Italy',cc:'🇮🇹',dl:['Master'],ft:'Partial',d:'2026-04-20',desc:'Merit-based scholarships for international students admitted to Laurea Magistrale (Master of Science) programmes at Polimi.',el:['International student','Admitted to MSc programme','Outstanding GPA'],ben:['Full tuition waiver','€10,000 annual grant'],req:['PoliMi online application','Academic transcripts','Motivation letter'],url:'https://www.polimi.it/en/international-prospective-students/merit-based-scholarships/',tags:['Italy','STEM','Engineering','Europe'],hc:'Italy',cat:'University',ca:'2024-11-01'},
{id:'50',t:'Mexican Government Scholarships (SRE)',u:'Various Mexican Universities',c:'Mexico',cc:'🇲🇽',dl:['Master','PhD'],ft:'Fully Funded',d:'2026-09-20',desc:'Mexican Government scholarships for foreign nationals to study graduate programs, research stays, or specialization at Mexican universities.',el:['Non-Mexican nationality','Bachelor\'s or Master\'s degree','Accepted by Mexican institution','Spanish proficiency (B2+)'],ben:['Monthly stipend','Health insurance','Tuition waiver','Registration fee waiver'],req:['SRE online application','Academic records','Spanish certificate','Letter of acceptance','Research plan'],url:'https://www.gob.mx/sre/acciones-y-programas/becas-del-gobierno-de-mexico-para-extranjeros',tags:['Mexico','Latin America','Research','Spanish'],hc:'Mexico',cat:'Government',ca:'2024-11-05'},
{id:'51',t:'Monash International Merit Scholarship',u:'Monash University',c:'Australia',cc:'🇦🇺',dl:['Bachelor','Master'],ft:'Partial',d:'2026-07-31',desc:'Merit-based scholarship for high-achieving international students commencing an undergraduate or graduate coursework degree at Monash.',el:['International student','Academic excellence','Unconditional offer from Monash'],ben:['$10,000 per year tuition reduction','Renewable based on academic performance'],req:['Monash application','Academic transcripts','Automatic consideration on admission'],url:'https://www.monash.edu/study/fees-scholarships/scholarships',tags:['Australia','Merit','Undergraduate'],hc:'Australia',cat:'University',ca:'2024-11-10'},
{id:'52',t:'Russian Government Scholarship',u:'Various Russian Universities',c:'Russia',cc:'🇷🇺',dl:['Bachelor','Master','PhD'],ft:'Fully Funded',d:'2026-02-20',desc:'The Russian Government provides scholarships for international students to pursue higher education at leading Russian universities.',el:['Foreign citizen','Secondary or higher education diploma','No age limit for most programmes','Russian language proficiency (or preparatory year)'],ben:['Tuition waiver','Monthly stipend','Dormitory accommodation'],req:['Online application via education-in-russia.com','Academic records','Medical certificate','Passport copy'],url:'https://education-in-russia.com/',tags:['Russia','All Levels','STEM','Arts'],hc:'Russia',cat:'Government',ca:'2024-11-15'},
{id:'53',t:'Nottingham Developing Solutions Scholarship',u:'University of Nottingham',c:'United Kingdom',cc:'🇬🇧',dl:['Master'],ft:'Fully Funded',d:'2026-05-18',desc:'For students from Africa, India and selected developing countries who want to study a master\'s degree and make a difference in their home country.',el:['Citizen of eligible developing country','Offer from Nottingham taught master\'s','Excellent academic record','Commitment to development impact'],ben:['100% tuition fee reduction (30 scholarships) or 50% (75 scholarships)'],req:['Nottingham application','Scholarship application essay','Academic records','Development impact statement'],url:'https://www.nottingham.ac.uk/studywithus/international-applicants/scholarships/developing-solutions.aspx',tags:['UK','Development','Africa','India'],hc:'United Kingdom',cat:'University',ca:'2024-11-20'},
{id:'54',t:'Oesterreichische Entwicklungszusammenarbeit (OeAD)',u:'Various Austrian Universities',c:'Austria',cc:'🇦🇹',dl:['Master','PhD'],ft:'Fully Funded',d:'2026-03-01',desc:'Austrian Development Cooperation scholarship programme for students from developing countries to study in Austria.',el:['Citizen of OeAD partner country','Under 35 years old','Relevant professional experience','Study plan aligned with development goals'],ben:['Monthly grant €1,050','Tuition waiver','Travel costs','Insurance','German language course'],req:['Online application','Academic records','Work experience proof','Motivation letter','German/English proficiency'],url:'https://www.grants.at/',tags:['Austria','Europe','Development'],hc:'Austria',cat:'Government',ca:'2024-11-25'},
{id:'55',t:'University of Edinburgh Global Scholarships',u:'University of Edinburgh',c:'United Kingdom',cc:'🇬🇧',dl:['Master'],ft:'Partial',d:'2026-04-15',desc:'A range of scholarships for international students applying to one-year taught master\'s programmes at the University of Edinburgh.',el:['International fee status','Offer from Edinburgh taught master\'s','Academic excellence'],ben:['£5,000–£10,000 tuition fee reduction per year'],req:['Edinburgh application','Scholarship application','Academic records','References'],url:'https://www.ed.ac.uk/student-funding/postgraduate/international',tags:['UK','Scotland','Postgraduate'],hc:'United Kingdom',cat:'University',ca:'2024-12-01'},
];
