import { CompactScholarship } from './scholarship-factory';

const LV = '2026-05-04';

export const GOV_BATCH2: CompactScholarship[] = [
  {
    id: 'gov2-1',
    t: 'Slovak Government Scholarship',
    on: 'Scholarships of the Government of the Slovak Republic',
    u: 'Ministry of Education, Research, Development and Youth of the Slovak Republic',
    c: 'Slovakia',
    cc: '🇸🇰',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Stipend',
    d: '2026-05-25',
    desc: 'Slovak Government Scholarships support selected foreign students under Slovakia\'s official development cooperation scholarship programme.',
    el: ['Citizen of a country and field listed in the official Slovak Government scholarship call', 'Meet admission requirements for the chosen Slovak higher education programme', 'Submit the online application by the official deadline'],
    ben: ['Monthly scholarship support', 'Study at Slovak higher education institutions', 'Financial terms defined by the official annual call'],
    cd: ['Government scholarship terms and amounts are published in the annual financial terms document', 'Support depends on study level and official country allocation'],
    req: ['Online application through vladnestipendia.sk', 'Eligible country and study field', 'Academic documents', 'Admission-related documents required by the call'],
    rdoc: ['Application form', 'Passport copy', 'Academic transcripts and certificates', 'CV', 'Motivation letter', 'Language or admission documents where required'],
    ap: ['Check the official annual country and field list', 'Register on vladnestipendia.sk', 'Complete the online application', 'Upload required documents before the deadline'],
    sc: ['Country allocation', 'Academic record', 'Programme fit', 'Completeness of documents'],
    tips: ['Use the Ministry page and vladnestipendia.sk only', 'Check the annual XLS list before assuming your country or field is eligible'],
    lr: ['Language requirements depend on the Slovak programme and study language'],
    ec: ['Countries listed in the official Slovak Government Scholarship annual call'],
    ic: [],
    ecn: 'Official Ministry source publishes an annual country and scholarship list; eligibility depends on that official list and the selected study field.',
    esu: 'https://www.minedu.sk/scholarships-of-the-government-of-the-slovak-republic/',
    url: 'https://www.vladnestipendia.sk/',
    osu: 'https://www.minedu.sk/scholarships-of-the-government-of-the-slovak-republic/',
    lv: LV,
    sn: '2026/2027 online applications are open from 23 March to 25 May 2026 according to the official Ministry notice.',
    tags: ['Slovakia', 'Government', 'Development Cooperation'],
    hc: 'Slovakia',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-2',
    t: 'Czech Government Scholarship',
    on: 'Government Scholarships for Developing Countries',
    u: 'Government of the Czech Republic',
    c: 'Czech Republic',
    cc: '🇨🇿',
    dl: ['Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2026-09-30',
    ide: true,
    desc: 'Czech Government Scholarships support selected developing-country citizens for follow-up master and doctoral studies at Czech public higher education institutions.',
    el: ['Citizen of an eligible developing country', 'Apply for eligible master or doctoral study in Czechia', 'Meet programme admission and language requirements'],
    ben: ['Tuition coverage for eligible programmes', 'Living expense subsidy', 'Health insurance support'],
    cd: ['Support for standard length of eligible master or doctoral study', 'Funding rules are set by the Czech Government scholarship call'],
    req: ['Electronic government scholarship application', 'Eligible citizenship', 'Academic documents', 'Admission and language documents'],
    rdoc: ['Application form', 'Passport', 'Diplomas and transcripts', 'CV', 'Motivation or study plan', 'Language proof if required'],
    ap: ['Read the official guidelines and FAQ', 'Submit the electronic application by the deadline', 'Complete any required university admission steps', 'Await government selection results'],
    sc: ['Formal eligibility', 'Academic performance', 'Development cooperation priorities', 'Programme fit'],
    tips: ['Use the official government scholarship application route', 'Confirm your study programme is eligible before applying'],
    lr: ['English-language master and doctoral programmes require proof set by the university'],
    ec: ['Belarus (democratic forces)', 'Bosnia and Herzegovina', 'Cambodia', 'Ethiopia', 'Georgia', 'Guatemala', 'Jordan', 'Nigeria', 'Rwanda', 'Sri Lanka', 'Ukraine', 'Zambia'],
    ic: [],
    ecn: 'Official Czech scholarship notices list the eligible countries for the 2026/2027 call; the 2027/2028 call is expected to open in summer 2026.',
    esu: 'https://www.fs.tul.cz/en/government-scholarships',
    url: 'https://www.fs.tul.cz/en/government-scholarships',
    osu: 'https://www.fs.tul.cz/en/government-scholarships',
    lv: LV,
    sn: 'The 2026/2027 call is closed; next call deadline is expected on 30 September 2026 according to official university notices referencing the government programme.',
    tags: ['Czech Republic', 'Government', 'Developing Countries'],
    hc: 'Czech Republic',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-3',
    t: 'Brunei Darussalam Government Scholarship',
    on: 'Government of Brunei Darussalam Scholarship to Foreign Students',
    u: 'Ministry of Foreign Affairs, Brunei Darussalam',
    c: 'Brunei',
    cc: '🇧🇳',
    dl: ['Bachelor', 'Master'],
    ft: 'Fully Funded',
    d: '2027-02-15',
    ide: true,
    desc: 'The Brunei Government Scholarship gives foreign students the opportunity to study diploma, undergraduate, or master programmes at selected Bruneian institutions.',
    el: ['Foreign student', 'Meet age and academic criteria for the chosen level', 'Apply to one of the eligible Brunei institutions'],
    ben: ['Tuition fee support', 'Allowance support defined in the official call', 'Study at selected Brunei institutions'],
    cd: ['Scholarship is tenable at UBD, UNISSA, UTB, KUPU SB, and Politeknik Brunei where applicable', 'Benefits are defined in the annual MFA application documents'],
    req: ['Official application form', 'Academic certificates', 'Valid passport', 'Endorsement or submission through required official route'],
    rdoc: ['Application form', 'Certified academic documents', 'Passport copy', 'Birth certificate', 'References or testimonials', 'Medical certificate where required'],
    ap: ['Download the official BDGS form', 'Complete and sign the application', 'Scan documents', 'Submit through the official MFA instructions before the deadline'],
    sc: ['Academic merit', 'Eligibility for chosen institution', 'Completeness of official documents'],
    tips: ['Use the MFA BDGS page and official forms only', 'Check institution programme availability before choosing courses'],
    lr: ['English or programme language requirements depend on the host institution'],
    ec: ['Foreign students'],
    ic: [],
    ecn: 'Official Brunei MFA service states the scholarship is for foreign students; the annual call and forms define any country-specific submission requirements.',
    esu: 'https://www.mfa.gov.bn/pages/online-bdgs.aspx/',
    url: 'https://www.mfa.gov.bn/pages/online-bdgs.aspx/',
    osu: 'https://www.mfa.gov.bn/pages/online-bdgs.aspx/',
    lv: LV,
    sn: 'The 2026/2027 application opened on 15 December 2025 and closed on 15 February 2026; next-cycle deadline is estimated.',
    tags: ['Brunei', 'Government', 'Foreign Students'],
    hc: 'Brunei',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-4',
    t: 'Malaysia International Scholarship',
    on: 'Malaysia International Scholarship (MIS)',
    u: 'Ministry of Higher Education Malaysia',
    c: 'Malaysia',
    cc: '🇲🇾',
    dl: ['Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-04-03',
    ide: true,
    desc: 'Malaysia International Scholarship is a Malaysian Government initiative for outstanding international graduates pursuing master or PhD study at Malaysian higher education institutions.',
    el: ['Citizen of a recipient country listed in the MIS guidelines', 'Intend to pursue or continue full-time postgraduate study in Malaysia', 'Strong academic and co-curricular record'],
    ben: ['Tuition fee support according to MIS rules', 'Monthly living allowance', 'Postgraduate study at participating Malaysian institutions'],
    cd: ['Funding is for full-time master or PhD study', 'Eligible universities and support terms are listed in official MIS guidelines'],
    req: ['MIS online application', 'Eligible recipient-country citizenship', 'Admission or study status documents', 'Academic and English evidence'],
    rdoc: ['Passport', 'Academic transcripts and certificates', 'Admission offer or enrolment evidence', 'CV', 'Research proposal for postgraduate study', 'English proficiency proof'],
    ap: ['Read the official MIS 2026 guidelines', 'Confirm recipient country and eligible university', 'Complete the MIS online application', 'Upload required documents before the deadline'],
    sc: ['Academic excellence', 'Research or study proposal quality', 'Leadership and co-curricular record', 'Institution eligibility'],
    tips: ['Use the MOHE MIS portal and PDF guidelines', 'Check the recipient-country list before preparing documents'],
    lr: ['English proficiency proof is required according to the official MIS guidelines'],
    ec: ['ASEAN countries', 'Commonwealth countries', 'Afghanistan', 'Albania', 'Algeria', 'Azerbaijan', 'Bahrain', 'Brazil', 'Chile', 'China', 'Egypt', 'Georgia', 'Hong Kong', 'Hungary', 'Iran', 'Iraq', 'Japan', 'Jordan', 'Kazakhstan', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Libya', 'Morocco', 'Palestine', 'Qatar', 'Russia', 'Saudi Arabia', 'Senegal', 'Serbia', 'South Korea', 'Sudan', 'Syria', 'Tajikistan', 'Timor-Leste', 'Tunisia', 'Türkiye', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Yemen'],
    ic: [],
    ecn: 'Official MIS 2026 guidelines list recipient countries, including ASEAN, Commonwealth regions, and additional named countries.',
    esu: 'https://biasiswa.mohe.gov.my/INTER/doc/MIS/Guidelines%20MIS%202026.pdf',
    url: 'https://biasiswa.mohe.gov.my/INTER/',
    osu: 'https://biasiswa.mohe.gov.my/INTER/',
    lv: LV,
    sn: 'The 2026/2027 call ran from 4 March to 3 April 2026; next-cycle deadline is estimated.',
    tags: ['Malaysia', 'Government', 'MIS', 'Postgraduate'],
    hc: 'Malaysia',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-5',
    t: 'Singapore International Graduate Award',
    on: 'Singapore International Graduate Award (SINGA)',
    u: 'A*STAR / Singapore Universities',
    c: 'Singapore',
    cc: '🇸🇬',
    dl: ['PhD'],
    ft: 'Fully Funded',
    d: '2026-12-01',
    ide: true,
    desc: 'SINGA supports international graduates pursuing PhD research in science and engineering through A*STAR and Singapore partner universities.',
    el: ['International graduate', 'Strong academic record', 'Interest in science and engineering research', 'Good English academic references'],
    ben: ['Tuition fee support', 'Monthly stipend', 'Airfare grant', 'Settlement allowance'],
    cd: ['PhD scholarship support through participating Singapore institutions', 'SIT-SINGA has January and August intake cycles'],
    req: ['Online SINGA application', 'Academic transcripts', 'Research interests', 'Referee reports'],
    rdoc: ['Passport', 'Bachelor and master transcripts where applicable', 'Degree certificates', 'Recommendation reports', 'Research interest selections'],
    ap: ['Review available projects and institutions', 'Submit online SINGA application', 'Arrange referee reports', 'Attend interviews if shortlisted'],
    sc: ['Academic excellence', 'Research potential', 'Fit with selected project', 'Referee reports'],
    tips: ['Shortlist research areas before applying', 'Ask referees early so reports arrive before deadline'],
    lr: ['English proficiency is assessed through academic records and references; host institutions may set additional requirements'],
    ec: ['All countries except listed exclusions'],
    ic: ['Singapore'],
    ecn: 'Official partner source states SINGA is open to international students, specifically non-Singaporeans and non-permanent residents.',
    esu: 'https://www.singaporetech.edu.sg/admissions/scholarships/singapore-international-graduate-award-singa',
    url: 'https://www.a-star.edu.sg/singa-award',
    osu: 'https://www.a-star.edu.sg/singa-award',
    lv: LV,
    sn: 'SIT-SINGA lists two annual intake cycles: January intake applications close 1 June and August intake applications close 1 December.',
    feat: true,
    tags: ['Singapore', 'Government', 'SINGA', 'PhD', 'STEM'],
    hc: 'Singapore',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-6',
    t: 'Taiwan MOE Scholarship',
    on: 'MOE Taiwan Scholarship',
    u: 'Taiwan Ministry of Education',
    c: 'Taiwan',
    cc: '🇹🇼',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Stipend',
    d: '2026-05-31',
    ide: true,
    desc: 'The MOE Taiwan Scholarship encourages outstanding international students to undertake degree studies in Taiwan through Taiwan overseas missions.',
    el: ['Foreign national applying through a participating Taiwan overseas mission', 'Apply for an eligible Taiwan degree programme', 'Meet MOE and university requirements'],
    ben: ['Tuition and miscellaneous expense subsidy', 'Monthly stipend for undergraduate or postgraduate study'],
    cd: ['Support level follows MOE Taiwan Scholarship directions', 'Application windows are managed by embassy or representative office'],
    req: ['Taiwan Scholarship application', 'University admission application', 'Academic records', 'Language documents required by the programme'],
    rdoc: ['Application form', 'Passport or nationality proof', 'Academic transcripts', 'Admission application proof', 'Language certificates', 'Study plan'],
    ap: ['Check the availability status for your Taiwan overseas mission', 'Apply to Taiwan universities separately', 'Submit scholarship documents to the mission by its deadline', 'Follow mission selection steps'],
    sc: ['Academic merit', 'Study plan', 'Mission quota and eligibility rules', 'University admission'],
    tips: ['Deadlines vary by embassy or representative office', 'Apply for university admission and scholarship in parallel'],
    lr: ['Chinese or English requirements depend on the Taiwan university programme'],
    ec: ['Countries served by participating Taiwan overseas missions'],
    ic: [],
    ecn: 'Official MOE availability page lists application windows by Taiwan overseas mission and country; applicants must use the mission responsible for their country.',
    esu: 'https://taiwanscholarship.moe.gov.tw/Apply/Enroll/availabilitystatus',
    url: 'https://taiwanscholarship.moe.gov.tw/',
    osu: 'https://edu.law.moe.gov.tw/EngLawContent.aspx?id=20494&lan=E',
    lv: LV,
    sn: 'The central system shows 2026 registration availability through 31 May 2026, while individual mission windows may vary.',
    tags: ['Taiwan', 'MOE', 'Government', 'All Levels'],
    hc: 'Taiwan',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-7',
    t: 'Mexican Government Scholarship for International Students',
    on: 'Mexican Government Scholarships for Foreigners',
    u: 'Secretariat of Foreign Affairs of Mexico (SRE)',
    c: 'Mexico',
    cc: '🇲🇽',
    dl: ['Master', 'PhD'],
    ft: 'Stipend',
    d: '2027-03-26',
    ide: true,
    desc: 'The Mexican Government offers scholarships for foreign nationals through SRE annual calls and the official Study in Mexico/SRE scholarship route.',
    el: ['Foreign national from a country or institution covered by the annual SRE call', 'Meet academic and Spanish requirements where applicable', 'Hold or obtain admission to an eligible Mexican institution'],
    ben: ['Monthly stipend', 'Health insurance', 'Tuition or registration support where provided', 'Support terms defined by annual call'],
    cd: ['Coverage depends on programme type and annual SRE call', 'Awards are for eligible Mexican institutions and study activities'],
    req: ['SRE online application', 'Academic documents', 'Admission or acceptance documents', 'Spanish proof where required'],
    rdoc: ['Application form', 'Passport', 'Academic transcripts', 'Acceptance letter', 'CV', 'Motivation letter', 'Spanish certificate where required'],
    ap: ['Check the official SRE scholarship call and eligible country list', 'Secure Mexican institution acceptance where required', 'Submit online application by the deadline', 'Follow SRE selection announcements'],
    sc: ['Academic merit', 'Institutional acceptance', 'Study or research proposal', 'Language readiness'],
    tips: ['Use the SRE and gob.mx pages only', 'Confirm the annual eligible countries list before applying'],
    lr: ['Spanish B2 or programme-specific language proof may be required'],
    ec: ['Eligible countries listed in the SRE call'],
    ic: [],
    ecn: 'Official SRE pages publish annual calls and eligible countries/institutions; exact country eligibility must be checked in the current SRE call.',
    esu: 'https://www.datos.gob.mx/dataset/becas_extranjeros_otorgadas_amexcid',
    url: 'https://www.datos.gob.mx/dataset/becas_extranjeros_otorgadas_amexcid',
    osu: 'https://www.datos.gob.mx/dataset/becas_extranjeros_otorgadas_amexcid',
    lv: LV,
    sn: 'Current exact deadline should be checked in the active SRE call; display date is estimated from recent government scholarship timing.',
    tags: ['Mexico', 'Government', 'SRE', 'Spanish'],
    hc: 'Mexico',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-8',
    t: 'Colombia Government Scholarship / ICETEX',
    on: 'Beca Colombia Extranjeros',
    u: 'ICETEX / Government of Colombia',
    c: 'Colombia',
    cc: '🇨🇴',
    dl: ['Master'],
    ft: 'Fully Funded',
    d: '2026-06-05',
    desc: 'Beca Colombia Extranjeros is an ICETEX reciprocity programme for foreign citizens who want to study Spanish courses, specializations, or master programmes in Colombia.',
    el: ['Foreign citizen', 'Apply for an eligible academic offer in Colombia', 'Meet ICETEX call documents and Spanish-language submission rules'],
    ben: ['Scholarship support according to the ICETEX call', 'Eligible study in Colombia', 'Support terms defined in the call documents'],
    cd: ['Coverage and academic catalogue are published in the active ICETEX call documents', '2026-2 call covers Spanish courses, specializations, and master programmes'],
    req: ['ICETEX online application', 'Documents required by the active call', 'Spanish translations where documents are in another language'],
    rdoc: ['Application form', 'Passport', 'Academic certificate and transcript', 'CV', 'Admission or programme documents', 'Spanish translations where required'],
    ap: ['Review ICETEX call bases and academic catalogue', 'Prepare documents in Spanish or with official translation', 'Submit through the ICETEX platform', 'Check published results'],
    sc: ['Formal eligibility', 'Academic profile', 'Programme fit', 'Completeness of documents'],
    tips: ['Read the English or Spanish call bases before applying', 'All documents must satisfy ICETEX formatting and translation rules'],
    lr: ['Spanish documentation and programme language requirements apply'],
    ec: ['Foreign citizens eligible under the ICETEX Beca Colombia call'],
    ic: ['Colombia'],
    ecn: 'Official ICETEX call is directed to foreigners; applicants must follow the active Beca Colombia Extranjeros call and academic catalogue.',
    esu: 'https://web.icetex.gov.co/becas/beca-colombia-extranjeros',
    url: 'https://web.icetex.gov.co/becas/beca-colombia-extranjeros',
    osu: 'https://web.icetex.gov.co/becas/beca-colombia-extranjeros',
    lv: LV,
    sn: 'The 2026-2 ICETEX call is open until 5 June 2026 at 17:00 Colombia time, with results scheduled for 18 June 2026.',
    tags: ['Colombia', 'Government', 'ICETEX', 'Spanish'],
    hc: 'Colombia',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-9',
    t: 'Thailand International Postgraduate Programme',
    on: 'Thailand International Postgraduate Programme (TIPP)',
    u: 'Thailand International Cooperation Agency / Ministry of Foreign Affairs',
    c: 'Thailand',
    cc: '🇹🇭',
    dl: ['Master'],
    ft: 'Fully Funded',
    d: '2027-02-23',
    ide: true,
    desc: 'TIPP is Thailand\'s development cooperation scholarship framework for master courses in SDG-related fields at Thai universities and academic institutions.',
    el: ['Citizen of an eligible TIPP country or territory', 'Nominated through the official route where required', 'Meet course-specific academic and professional requirements'],
    ben: ['Return economy airfare', 'Monthly subsistence allowance', 'Settlement, books, and thesis allowances', 'Tuition and programme support as defined by TICA'],
    cd: ['Fully funded master-level courses under annual TIPP list', 'Each course has its own theme, institution, duration, and deadline'],
    req: ['TIPP application form', 'Nomination route documents where required', 'Academic records', 'Medical and language documents as required'],
    rdoc: ['Application form', 'Passport', 'Academic transcripts and certificates', 'English proficiency evidence', 'Medical report', 'Employer or nomination documents where required'],
    ap: ['Check the TIPP course list and eligible countries', 'Prepare course-specific documents', 'Submit online or through the official nomination route', 'Follow TICA selection instructions'],
    sc: ['Country eligibility', 'Academic and professional fit', 'Relevance to sustainable development priorities', 'Course-specific requirements'],
    tips: ['Choose a course before preparing documents because requirements differ', 'Check whether your country requires nomination through a government office or Thai embassy'],
    lr: ['English proficiency is typically required for international master courses'],
    ec: ['TIPP eligible countries and territories'],
    ic: [],
    ecn: 'Official TICA page links a dedicated list of eligible countries for TIPP; eligibility and nomination rules are country-specific.',
    esu: 'https://tica-thaigov.mfa.go.th/en/page/list-of-eligible-countries-for-tipp?menu=605b13d42a9d1e3f537649e2',
    url: 'https://tica-thaigov.mfa.go.th/en/content/tipp-2027?cate=605b1025f07513674238a233',
    osu: 'https://tica-thaigov.mfa.go.th/en/content/tipp-2027?cate=605b1025f07513674238a233',
    lv: LV,
    sn: 'The 2026 TIPP course list used 23 February 2026 as the common closing date; next-cycle date is estimated.',
    tags: ['Thailand', 'Government', 'TICA', 'Postgraduate'],
    hc: 'Thailand',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov2-10',
    t: 'Indonesia KNB Scholarship',
    on: 'Kemitraan Negara Berkembang (KNB) Scholarship',
    u: 'Ministry of Higher Education, Science, and Technology of Indonesia',
    c: 'Indonesia',
    cc: '🇮🇩',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2027-03-31',
    ide: true,
    desc: 'KNB Scholarship is an Indonesian Government scholarship for students from developing countries to study bachelor, master, or doctoral programmes at Indonesian universities.',
    el: ['Citizen of an eligible developing country', 'Meet age and degree requirements for the chosen level', 'Secure recommendation and admission-related documents required by KNB'],
    ben: ['Tuition fee support', 'Monthly living allowance', 'Health insurance', 'Settlement and book allowances according to KNB rules'],
    cd: ['Full-degree support at participating Indonesian universities', 'Benefits and timeline are published in the official KNB portal and guidebook'],
    req: ['KNB online application', 'Embassy verification or recommendation route', 'Academic documents', 'English proficiency proof', 'University acceptance process'],
    rdoc: ['Passport', 'Academic certificates and transcripts', 'Recommendation letters', 'English test certificate', 'Health certificate', 'Motivation statement', 'Acceptance or recommendation documents where required'],
    ap: ['Check the official KNB portal', 'Prepare documents and recommendation route', 'Submit online application', 'Complete embassy and directorate verification', 'Follow academic selection results'],
    sc: ['Academic record', 'Country eligibility', 'Document verification', 'Programme fit', 'Interview or academic selection where used'],
    tips: ['Start university and embassy documents early', 'Use only the official KNB portal and ministry instructions'],
    lr: ['English proficiency proof is required; Indonesian language preparation may be part of the scholarship path'],
    ec: ['KNB eligible developing countries'],
    ic: [],
    ecn: 'Official KNB portal is the authoritative source for the annual eligible developing-country list and application guide.',
    esu: 'https://knb.kemdiktisaintek.go.id/',
    url: 'https://knb.kemdiktisaintek.go.id/',
    osu: 'https://knb.kemdiktisaintek.go.id/',
    lv: LV,
    sn: 'The 2026 official KNB timeline closed on 31 March 2026; next-cycle deadline is estimated until the next official guide is published.',
    tags: ['Indonesia', 'Government', 'KNB', 'Developing Countries'],
    hc: 'Indonesia',
    cat: 'Government',
    ca: '2026-05-04',
  },
];
