import { CompactScholarship } from './scholarship-factory';

export const BATCH_RUSSIA: CompactScholarship[] = [
  {
    id: '60',
    t: 'Open Doors Russian Scholarship Project',
    on: 'Open Doors: Russian Scholarship Project',
    u: 'Various Russian Universities',
    c: 'Russia',
    cc: '🇷🇺',
    dl: ['Bachelor', 'Master', 'PhD', 'Postdoc'],
    ft: 'Fully Funded',
    d: '2026-12-01',
    ide: true,
    desc: 'Open Doors is an international online competition (olympiad) for prospective international students. Winners and prize-winners may receive the right to tuition-free study at leading Russian universities under the Russian Government quota. It is not a traditional scholarship application — it is a competitive selection with portfolio evaluation, subject tasks, and interviews depending on the track.',
    el: [
      'Foreign citizen or stateless person',
      'Bachelor track: age 16–23, with completed or ongoing secondary education',
      'Master track: age 20–33, with completed or ongoing bachelor\'s degree',
      'Doctoral track: age 22–35, with completed or ongoing master\'s degree',
      'Postdoctoral track: up to age 39, with a PhD/candidate degree',
      'Each track has specific education-level requirements',
    ],
    ben: [
      'Tuition-free study at a Russian university under the Government quota',
      'Some universities may offer dormitory placement',
      'Stipend may be available depending on the university',
    ],
    cd: [
      'Tuition waiver under the Russian Government quota for winners',
      'Dormitory placement may be offered by the host university',
      'Monthly stipend availability varies by university',
    ],
    req: [
      'Online registration on od.globaluni.ru',
      'Motivation letter (mandatory, first stage)',
      'Proof of education level (mandatory, first stage)',
      'Optional portfolio documents to increase score',
    ],
    rdoc: [
      'Motivation letter',
      'Proof of education level (diploma, certificate, or enrollment confirmation)',
      'Portfolio documents (optional, but recommended to improve score)',
      'Passport or ID document',
    ],
    ap: [
      'Register on the official Open Doors platform (od.globaluni.ru)',
      'Select your track (Bachelor, Master, Doctoral, or Postdoctoral)',
      'Upload mandatory documents: motivation letter and proof of education level',
      'Optionally upload portfolio documents to increase your score',
      'First stage: portfolio evaluation by experts',
      'Second stage: subject-specific tasks or interviews depending on the track',
      'Winners receive the right to tuition-free enrollment under the Russian Government quota',
    ],
    sc: [
      'Portfolio quality and relevance to the chosen track',
      'Motivation letter strength',
      'Performance on subject-specific evaluation tasks',
      'Interview performance (for some tracks)',
    ],
    tips: [
      'Invest time in a strong portfolio — it is the most important factor in the first stage',
      'Write a focused motivation letter explaining your academic goals and why Russia',
      'Choose your track carefully based on your current education level',
      'Optional portfolio documents can significantly increase your score — include them',
      'Prepare for subject-specific tasks relevant to your field of study',
    ],
    lr: [
      'Russian or English depending on the chosen programme',
      'Russian language preparatory courses may be available at some universities',
    ],
    url: 'https://od.globaluni.ru/',
    osu: 'https://od.globaluni.ru/rules',
    lv: '2026-04-29',
    sn: 'Official rules verified at od.globaluni.ru/rules. Exact deadline varies by track and academic year — check the official website for current dates.',
    feat: true,
    tags: ['Russia', 'Olympiad', 'All Levels', 'Government Quota'],
    hc: 'Russia',
    cat: 'Government',
    ca: '2024-12-01',
  },
  {
    id: '61',
    t: 'Russian Government Scholarship (Government Quota)',
    on: 'Russian Government Scholarship for Foreign Citizens (Quota)',
    u: 'Various Russian Universities',
    c: 'Russia',
    cc: '🇷🇺',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Fully Funded',
    d: '2026-03-15',
    ide: true,
    desc: 'The Russian Government allocates quota places for international students to study at Russian universities with tuition fees covered by the federal budget. Applications are submitted through the official Education in Russia portal or through Russian embassies/representative offices in the applicant\'s country. Specific requirements and document lists may vary by country and representative office.',
    el: [
      'Foreign citizen or compatriot living abroad',
      'Secondary education diploma (for bachelor\'s) or higher education diploma (for master\'s/PhD)',
      'Must meet the admission requirements of the chosen university and programme',
      'Eligibility criteria may vary by country and representative office',
    ],
    ben: [
      'Tuition fees covered by the Russian federal budget',
      'Dormitory accommodation may be provided',
      'Monthly stipend may be available (amount varies by region and university)',
    ],
    cd: [
      'Tuition waiver from the Russian federal budget',
      'Dormitory placement (availability varies by university)',
      'Monthly stipend (varies by university and region)',
    ],
    req: [
      'Registration on education-in-russia.com portal',
      'Personal identification document (passport)',
      'Education diploma or certificate with grades',
      'Medical documents (may be required)',
      'Additional documents as specified by the country representative office',
    ],
    rdoc: [
      'Passport or national ID',
      'Education diploma with transcript/grades',
      'Medical certificate (requirements vary)',
      'Translated and notarized copies of documents if required',
      'Completed online application on education-in-russia.com',
    ],
    ap: [
      'Register and create an account on education-in-russia.com',
      'Enter personal information and upload documents',
      'Choose preferred programmes and universities (up to 6 options)',
      'Submit the completed application',
      'Alternatively, apply through the Russian Embassy or representative office in your country',
      'Await selection results from the representative office or Rossotrudnichestvo',
    ],
    sc: [
      'Academic record and grades',
      'Compliance with programme requirements',
      'Results of selection tests (if applicable)',
      'Selection criteria may vary by country and representative office',
    ],
    tips: [
      'Apply through education-in-russia.com — it is the official government portal',
      'Check with the Russian Embassy in your country for country-specific deadlines and procedures',
      'Choose up to 6 programmes/universities to increase your chances',
      'Some countries have additional selection stages — contact the local representative office early',
      'Document requirements vary by country — confirm the exact list with your representative office',
    ],
    lr: [
      'Russian language proficiency may be required for Russian-taught programmes',
      'A preparatory year (including Russian language) may be offered before the main programme',
      'English-taught programmes are available at some universities',
    ],
    url: 'https://education-in-russia.com/',
    osu: 'https://education-in-russia.com/',
    lv: '2026-04-29',
    sn: 'Application process and requirements may vary by country and representative office. Stipend and dormitory benefits are not guaranteed for all universities. Check education-in-russia.com for the latest information.',
    tags: ['Russia', 'Government', 'All Levels', 'Government Quota'],
    hc: 'Russia',
    cat: 'Government',
    ca: '2024-12-05',
  },
  {
    id: '62',
    t: 'HSE University International Tuition Discounts',
    on: 'HSE University Scholarships and Tuition Discounts for International Students',
    u: 'HSE University (Higher School of Economics)',
    c: 'Russia',
    cc: '🇷🇺',
    dl: ['Bachelor', 'Master'],
    ft: 'Partial',
    d: '2026-06-30',
    ide: true,
    desc: 'HSE University offers tuition discounts and partial scholarships for international students admitted to bachelor\'s and master\'s programmes. The discounts range from 25% to 100% of tuition fees depending on entrance exam results, portfolio assessment, olympiad performance, or academic record. HSE does not offer a single universal fully funded scholarship — funding levels depend on individual performance and programme.',
    el: [
      'Foreign citizen applying to an HSE bachelor\'s or master\'s programme',
      'Must meet admission requirements for the specific programme',
      'Discount level depends on entrance exam score, portfolio, or olympiad results',
      'Some programmes have additional requirements (e.g., specific subjects, language tests)',
    ],
    ben: [
      'Tuition discount ranging from 25% to 100% depending on performance',
      'Some programmes offer additional academic scholarships based on ongoing GPA',
      'Dormitory accommodation available at a subsidized rate',
    ],
    cd: [
      'Tuition discount of 25% to 100% (depends on entrance exam/portfolio results)',
      'Additional academic scholarships possible based on ongoing academic performance',
      'Subsidized dormitory accommodation',
    ],
    req: [
      'Online application through HSE admissions portal (admissions.hse.ru)',
      'Education diploma or certificate with grades',
      'Passport copy',
      'Portfolio or entrance exam results (depending on the programme)',
      'Language proficiency certificate (English or Russian depending on programme)',
    ],
    rdoc: [
      'Completed online application on admissions.hse.ru',
      'Education diploma with transcript',
      'Passport copy',
      'Portfolio documents (if applicable)',
      'Language certificate (IELTS, TOEFL, or equivalent for English-taught; TORFL for Russian-taught)',
    ],
    ap: [
      'Apply through the official HSE admissions portal at admissions.hse.ru',
      'Select the programme and track (fee-paying or quota)',
      'Submit required documents and portfolio',
      'Take entrance exams if required by the programme',
      'Tuition discount is determined based on exam/portfolio results',
      'Admission decision and discount level communicated by HSE',
    ],
    sc: [
      'Entrance exam score or portfolio assessment results',
      'Academic record (GPA, class ranking)',
      'Olympiad results (if applicable — some olympiads grant direct admission or higher discounts)',
      'Programme-specific criteria',
    ],
    tips: [
      'Check each programme\'s admission page on hse.ru for specific requirements and deadlines',
      'Strong entrance exam performance directly determines your discount level',
      'Participating in recognized olympiads can lead to higher discounts or direct admission',
      'Apply early — some programmes fill up before the general deadline',
      'HSE has both English-taught and Russian-taught programmes — choose based on your language skills',
    ],
    lr: [
      'English proficiency (IELTS 6.5+ or TOEFL 80+) for English-taught programmes',
      'Russian proficiency (TORFL certificate or equivalent) for Russian-taught programmes',
    ],
    url: 'https://admissions.hse.ru/en/',
    osu: 'https://admissions.hse.ru/en/',
    lv: '2026-04-29',
    sn: 'HSE tuition discounts are not a single scholarship — the funding level varies by programme and individual performance. Check admissions.hse.ru for the most current information on each programme.',
    tags: ['Russia', 'Partial Funding', 'University', 'Tuition Discount'],
    hc: 'Russia',
    cat: 'University',
    ca: '2024-12-10',
  },
];
