import { CompactScholarship } from './scholarship-factory';

const E = ['Academic transcripts','Letters of recommendation','Language proficiency certificate'];
const R = ['Online application form','CV/Resume','Personal statement'];

export const BATCH2: CompactScholarship[] = [
{id:'31',t:'Brunei Darussalam Government Scholarship',u:'Universiti Brunei Darussalam',c:'Brunei',cc:'🇧🇳',dl:['Bachelor','Master'],ft:'Fully Funded',d:'2026-02-15',desc:'Brunei Darussalam Government Scholarship for foreign students to study at universities in Brunei.',el:['Age 18-25 (BA), under 35 (MA)','Good health','Academic excellence',...E],ben:['Full tuition','Monthly allowance','Accommodation','Air tickets','Medical benefits'],req:[...R,'Medical report','Police clearance'],url:'https://www.moe.gov.bn/',tags:['Brunei','Asia','Government'],hc:'Brunei',cat:'Government',ca:'2024-08-01'},
{id:'32',t:'CSC Scholarship (Chinese Government)',u:'Various Chinese Universities',c:'China',cc:'🇨🇳',dl:['Bachelor','Master','PhD'],ft:'Fully Funded',d:'2026-01-31',desc:'Chinese Government Scholarship managed by China Scholarship Council, one of the largest scholarship programs in the world.',el:['Non-Chinese citizen','Good health','Age limits vary by level','Meet academic requirements',...E],ben:['Tuition waiver','Accommodation','Monthly stipend','Medical insurance'],req:[...R,'Study/research plan','Physical examination form'],url:'https://www.csc.edu.cn/',feat:true,tags:['China','Asia','All Levels','STEM'],hc:'China',cat:'Government',ca:'2024-08-05'},
{id:'33',t:'Endeavour Leadership Program',u:'Various Australian Universities',c:'Australia',cc:'🇦🇺',dl:['Master','PhD','Postdoc'],ft:'Fully Funded',d:'2026-06-30',desc:'Australian Government programme supporting international students, researchers, and professionals to undertake study and research in Australia.',el:['Any nationality','Academic excellence','Commence within program timeframe',...E],ben:['Up to AUD $272,500 total','Tuition fees','Travel allowance','Monthly stipend','Health insurance'],req:[...R,'Research proposal','Supervisor confirmation'],url:'https://www.education.gov.au/',tags:['Australia','Research','Leadership'],hc:'Australia',cat:'Government',ca:'2024-08-10'},
{id:'34',t:'Konrad-Adenauer-Stiftung Scholarship',u:'Various German Universities',c:'Germany',cc:'🇩🇪',dl:['Master','PhD'],ft:'Stipend',d:'2026-07-15',desc:'KAS supports gifted international students who pursue graduate degrees in Germany and show social or political engagement.',el:['International student in Germany','Active social/political engagement','Academic excellence','German language proficiency'],ben:['Monthly stipend €934','Study allowance €300/month','Health insurance subsidy','Language course support'],req:['Online application','Academic records','Two references','Proof of engagement','German B2 certificate'],url:'https://www.kas.de/en/web/begabtenfoerderung',tags:['Germany','Political','Social Engagement','Europe'],hc:'Germany',cat:'Foundation',ca:'2024-08-15'},
{id:'35',t:'Emile Boutmy Scholarship',u:'Sciences Po',c:'France',cc:'🇫🇷',dl:['Bachelor','Master'],ft:'Partial',d:'2026-05-02',desc:'Sciences Po scholarship for the most outstanding international students from outside the EU, named after the founder of Sciences Po.',el:['Non-EU nationality','First-time application to Sciences Po','Academic excellence','Financial need'],ben:['Tuition reduction up to €13,190/year (BA) or €12,200/year (MA)','Can include living grant of €5,000/year'],req:['Sciences Po application','Financial documentation','Academic records','Motivation letter'],url:'https://www.sciencespo.fr/en/admissions/financial-aid/',tags:['France','Social Sciences','Europe','Undergraduate'],hc:'France',cat:'University',ca:'2024-08-20'},
{id:'36',t:'Heinrich Böll Foundation Scholarship',u:'Various German Universities',c:'Germany',cc:'🇩🇪',dl:['Master','PhD'],ft:'Stipend',d:'2026-09-01',desc:'Heinrich Böll Foundation supports students committed to green values: ecology, democracy, solidarity, and non-violence.',el:['Enrolled in German university','Strong academic record','Engagement with green/social causes','International students eligible'],ben:['€934/month stipend','Book allowance €300/month','Family supplement if applicable','Health insurance'],req:['Online application','Academic records','Political/social engagement proof','German language certificate','Two references'],url:'https://www.boell.de/en/scholarships',tags:['Germany','Sustainability','Green','Europe'],hc:'Germany',cat:'Foundation',ca:'2024-08-25'},
{id:'37',t:'University of Melbourne Graduate Research Scholarships',u:'University of Melbourne',c:'Australia',cc:'🇦🇺',dl:['Master','PhD'],ft:'Fully Funded',d:'2026-10-31',desc:'Competitive scholarships for domestic and international students undertaking graduate research degrees at the University of Melbourne.',el:['Admitted to a graduate research degree','Honours degree or equivalent','Research proposal accepted by faculty'],ben:['Full fee remission','Living allowance (AUD $37,000+/year)','Relocation grant','OSHC for international students'],req:['Graduate research application','Research proposal','Academic transcripts','Two academic referees'],url:'https://scholarships.unimelb.edu.au/',tags:['Australia','Research','PhD','STEM'],hc:'Australia',cat:'University',ca:'2024-09-01'},
{id:'38',t:'Lester B. Pearson International Scholarship (UofT)',u:'University of Toronto',c:'Canada',cc:'🇨🇦',dl:['Bachelor'],ft:'Fully Funded',d:'2026-11-15',desc:'Recognizes international students who demonstrate exceptional academic achievement and creativity, and are recognized as leaders within their school.',el:['International student','Last year of secondary school or recently graduated','Nominated by school','Outstanding academic achievement'],ben:['Full tuition, books, incidental fees, and residence for 4 years'],req:['School nomination','UofT application','Academic transcripts','Personal profile'],url:'https://future.utoronto.ca/pearson/',tags:['Canada','Undergraduate','Leadership','Prestigious'],hc:'Canada',cat:'University',ca:'2024-09-05'},
{id:'39',t:'Friedrich Ebert Stiftung Scholarship',u:'Various German Universities',c:'Germany',cc:'🇩🇪',dl:['Master','PhD'],ft:'Stipend',d:'2026-05-31',desc:'FES supports talented international students in Germany who demonstrate commitment to social democracy and social justice.',el:['International student enrolled in Germany','Social/political engagement','Academic excellence','Financial need'],ben:['€850/month stipend','Study allowance','Health insurance subsidy','Networking events'],req:['Online application','Academic records','Proof of engagement','Two references','German language skills'],url:'https://www.fes.de/en/scholarship',tags:['Germany','Social Justice','Democracy','Europe'],hc:'Germany',cat:'Foundation',ca:'2024-09-10'},
{id:'40',t:'Singapore International Graduate Award (SINGA)',u:'Various Singapore Universities',c:'Singapore',cc:'🇸🇬',dl:['PhD'],ft:'Fully Funded',d:'2026-06-01',desc:'SINGA is a collaboration between A*STAR, NTU, NUS, SMU, and SUTD for international students to pursue PhD studies in science and engineering.',el:['Good Bachelor\'s or Master\'s degree','Passion for research','Strong English proficiency','Good academic references'],ben:['Full tuition fees','Monthly stipend of S$2,500 (up to S$3,000 after qualifying exam)','Airfare grant','Settlement allowance'],req:['Online SINGA application','Academic transcripts','Research interests statement','2 reference letters','GRE scores (optional)'],url:'https://www.a-star.edu.sg/singa-award',tags:['Singapore','PhD','STEM','Research','Asia'],hc:'Singapore',cat:'Government',ca:'2024-09-15'},
{id:'41',t:'Netherlands Fellowship Programme (NFP)',u:'Various Dutch Universities',c:'Netherlands',cc:'🇳🇱',dl:['Master'],ft:'Fully Funded',d:'2026-03-15',desc:'Dutch government scholarship for professionals from developing countries to follow short courses, master\'s programmes in the Netherlands.',el:['Citizen of NFP country list','Minimum 2 years work experience','Employer endorsement','Under 45 years old'],ben:['Tuition fees','Living costs','International travel','Visa costs','Insurance'],req:['Online application','Employer endorsement letter','Motivation letter','Academic transcripts','English proficiency'],url:'https://www.nuffic.nl/en/subjects/netherlands-fellowship-programmes',tags:['Netherlands','Development','Professional','Europe'],hc:'Netherlands',cat:'Government',ca:'2024-09-20'},
{id:'42',t:'KAIST International Student Scholarship',u:'KAIST',c:'South Korea',cc:'🇰🇷',dl:['Master','PhD'],ft:'Fully Funded',d:'2026-05-22',desc:'Korea Advanced Institute of Science and Technology offers full scholarships to international graduate students in STEM fields.',el:['International student','Bachelor\'s or Master\'s degree','Strong academic record in STEM'],ben:['Full tuition','Monthly living allowance','Airfare (one-time)','Medical insurance','Korean language course'],req:['Online application','Academic transcripts','Research plan','2 recommendation letters','English proficiency'],url:'https://admission.kaist.ac.kr/',tags:['South Korea','STEM','Research','Asia','Technology'],hc:'South Korea',cat:'University',ca:'2024-09-25'},
{id:'43',t:'Belgium VLIR-UOS Scholarships',u:'Various Belgian Universities',c:'Belgium',cc:'🇧🇪',dl:['Master'],ft:'Fully Funded',d:'2026-02-01',desc:'VLIR-UOS offers scholarships for students from developing countries to follow English-taught master\'s programmes at Flemish universities.',el:['Citizen of VLIR-UOS partner country','Max 35 years old','Relevant professional experience','Return to home country'],ben:['Tuition fees','Monthly allowance €1,090','International travel','Insurance'],req:['Online application','Academic transcripts','Motivation letter','Work experience proof','English proficiency'],url:'https://www.vliruos.be/',tags:['Belgium','Europe','Development'],hc:'Belgium',cat:'Government',ca:'2024-10-01'},
{id:'44',t:'ADB-Japan Scholarship Program',u:'Various Asian Universities',c:'Japan',cc:'🇯🇵',dl:['Master'],ft:'Fully Funded',d:'2026-04-01',desc:'Joint scholarship by Asian Development Bank and Japan providing study opportunities for citizens of ADB developing member countries.',el:['Citizen of ADB developing member country','Bachelor\'s degree','2+ years professional experience','Under 35','Admission to partner university'],ben:['Full tuition','Monthly subsistence and housing','Books and materials','Medical insurance','Travel costs'],req:['ADB-JSP application','University admission','Professional experience proof','Academic records'],url:'https://www.adb.org/work-with-us/careers/japan-scholarship-program',tags:['Japan','Asia','Development','Economics'],hc:'Japan',cat:'Foundation',ca:'2024-10-05'},
{id:'45',t:'Leiden University Excellence Scholarship (LExS)',u:'Leiden University',c:'Netherlands',cc:'🇳🇱',dl:['Master'],ft:'Partial',d:'2026-02-01',desc:'LExS is available for non-EU/EEA students who have been admitted to a Leiden University master\'s programme.',el:['Non-EU/EEA nationality','Academic excellence (top 10% of class)','Admitted to Leiden Master\'s'],ben:['€10,000 tuition fee reduction OR €15,000 reduction OR total tuition waiver minus €5,000'],req:['Leiden application','Scholarship essay','Academic transcripts','CV'],url:'https://www.universiteitleiden.nl/en/scholarships',tags:['Netherlands','Europe','Excellence'],hc:'Netherlands',cat:'University',ca:'2024-10-10'},
];
