import { CompactScholarship } from './scholarship-factory';

const LV = '2026-05-04';

export const GOV_BATCH3: CompactScholarship[] = [
  {
    id: 'gov3-1',
    t: 'Netherlands NL Scholarship',
    on: 'NL Scholarship',
    u: 'Dutch Ministry of Education, Culture and Science / Participating Dutch institutions',
    c: 'Netherlands',
    cc: '🇳🇱',
    dl: ['Bachelor', 'Master'],
    ft: 'Partial',
    d: '2026-05-01',
    ide: true,
    desc: 'The NL Scholarship is co-financed by the Dutch Ministry of Education, Culture and Science and participating Dutch higher education institutions for non-EEA students.',
    el: ['Non-EEA nationality', 'Apply to a full-time bachelor or master programme at a participating Dutch institution', 'Never previously enrolled for a degree in the Netherlands', 'Meet institution-specific criteria'],
    ben: ['One-time scholarship contribution', 'Usually EUR 5,000 for the first year', 'Institution-administered award'],
    cd: ['Not a full scholarship', 'Amount, participating programmes, and deadline vary by institution'],
    req: ['Admission application to participating institution', 'Scholarship application or automatic consideration depending on institution', 'Academic merit evidence'],
    rdoc: ['Admission documents', 'Academic transcripts', 'Passport', 'Motivation statement if required', 'Institution scholarship form if required'],
    ap: ['Choose a participating Dutch institution', 'Check its NL Scholarship page', 'Apply for the study programme', 'Submit scholarship materials by the institution deadline'],
    sc: ['Academic excellence', 'Institution-specific requirements', 'Programme fit', 'Non-EEA fee status'],
    tips: ['There is no single central application route', 'Check each university deadline and faculty rules'],
    lr: ['Language requirements depend on the host programme'],
    ec: ['All countries except listed exclusions'],
    ic: ['EEA countries'],
    ecn: 'Official institution pages state the NL Scholarship is for international students from outside the European Economic Area.',
    esu: 'https://www.uu.nl/en/masters/general-information/application-and-admission/scholarships-and-grants/nl-scholarship',
    url: 'https://www.studyinnl.org/finances/nl-scholarship',
    osu: 'https://www.uu.nl/en/masters/general-information/application-and-admission/scholarships-and-grants/nl-scholarship',
    lv: LV,
    sn: 'Government co-financed but administered by participating Dutch institutions; deadline shown is a common institutional deadline and varies by university.',
    tags: ['Netherlands', 'Government Co-Funded', 'Non-EEA', 'NL Scholarship'],
    hc: 'Netherlands',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-2',
    t: 'France Charpak Scholarship',
    on: 'Charpak Scholarship Program',
    u: 'Embassy of France in India / Campus France India',
    c: 'France',
    cc: '🇫🇷',
    dl: ['Bachelor', 'Master'],
    ft: 'Stipend',
    d: '2026-04-30',
    ide: true,
    desc: 'Charpak is an Embassy of France in India scholarship programme for Indian students pursuing study or exchange opportunities in France.',
    el: ['Indian national residing in India', 'Apply for an eligible French institution or exchange programme', 'Meet age, admission, and programme rules for the selected Charpak track'],
    ben: ['Monthly living allowance or fee support depending on track', 'Student visa fee waiver where applicable', 'Social security and Campus France support where listed'],
    cd: ['Benefits differ by Charpak track such as Master, Bachelor, Lab, or Exchange', 'Awards are not a central all-country France scholarship'],
    req: ['Campus France/Charpak application', 'Admission or exchange acceptance where required', 'Academic record', 'Statement of purpose'],
    rdoc: ['Passport', 'CV', 'Academic transcripts', 'Admission or NOC documents', 'Statement of purpose', 'Recommendation letters where required'],
    ap: ['Select the relevant Charpak track', 'Prepare academic and admission documents', 'Apply through the official Campus France India route', 'Wait for Embassy/Campus France results'],
    sc: ['Academic merit', 'Quality of study plan', 'French institution fit', 'Track-specific requirements'],
    tips: ['Choose the Charpak track carefully because benefits and documents differ', 'Apply to the French institution early'],
    lr: ['English or French requirements depend on the French programme'],
    ec: ['India'],
    ic: [],
    ecn: 'Official Charpak programme is administered by the Embassy of France in India/Campus France India and is for Indian students.',
    esu: 'https://www.inde.campusfrance.org/charpak-scholarships',
    url: 'https://www.inde.campusfrance.org/charpak-scholarships',
    osu: 'https://www.inde.campusfrance.org/charpak-scholarships',
    lv: LV,
    sn: 'Embassy/Campus France India programme, not a worldwide French central government scholarship; deadlines vary by Charpak track and annual call.',
    tags: ['France', 'India', 'Embassy Scholarship', 'Charpak'],
    hc: 'France',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-3',
    t: 'Belgium ARES Scholarships',
    on: 'ARES International Training Scholarships',
    u: 'ARES / Wallonia-Brussels Federation',
    c: 'Belgium',
    cc: '🇧🇪',
    dl: ['Bachelor', 'Master'],
    ft: 'Fully Funded',
    d: '2026-09-19',
    ide: true,
    desc: 'ARES international training scholarships fund selected specialised bachelor, specialised master, and continuing education courses in Belgium for partner-country professionals.',
    el: ['Citizen, resident, and working in an ARES partner country', 'Relevant academic background and professional experience', 'Apply to an eligible ARES international training course'],
    ben: ['International travel', 'Living allowance', 'Tuition and insurance support', 'Course-related support according to ARES rules'],
    cd: ['Funding depends on selected bachelor, master, or continuing education course', 'Administered by ARES as Belgian academic development cooperation'],
    req: ['ARES online application', 'Eligible partner-country status', 'Academic documents', 'Professional experience evidence'],
    rdoc: ['Application form', 'Passport', 'Diplomas and transcripts', 'CV', 'Employment certificates', 'Motivation and recommendation documents'],
    ap: ['Review the active ARES international training call', 'Choose an eligible course', 'Submit online application before the Belgian-time deadline', 'Await ARES selection results'],
    sc: ['Development relevance', 'Professional experience', 'Academic background', 'Motivation and course fit'],
    tips: ['Check the active call because eligible courses and countries can change', 'Show how training will support development impact in your country'],
    lr: ['French or English requirements depend on the selected course'],
    ec: ['ARES partner countries'],
    ic: [],
    ecn: 'Official ARES calls restrict eligibility to partner countries listed in the active call; applicants must confirm their country and course in the official ARES call.',
    esu: 'https://ares-ac.be/en/current-calls?annee=2026',
    url: 'https://ares-ac.be/en/current-calls?annee=2026',
    osu: 'https://ares-ac.be/en/current-calls?annee=2026',
    lv: LV,
    sn: 'Government-supported academic cooperation scholarship through ARES/Wallonia-Brussels, not a single federal Belgium scholarship for all international students.',
    tags: ['Belgium', 'ARES', 'Development', 'Government Supported'],
    hc: 'Belgium',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-4',
    t: 'Denmark Government Scholarships',
    on: 'Danish Government Scholarship Programme',
    u: 'Danish Government / Danish higher education institutions',
    c: 'Denmark',
    cc: '🇩🇰',
    dl: ['Bachelor', 'Master'],
    ft: 'Partial',
    d: '2026-02-01',
    ide: true,
    desc: 'Danish Government Scholarships are limited institution-administered awards for highly qualified non-EU/EEA students at selected Danish programmes.',
    el: ['Non-EU/EEA and non-Swiss citizen', 'Apply to a participating eligible Danish programme', 'Meet institution admission and scholarship criteria'],
    ben: ['Tuition fee waiver or reduction', 'Possible monthly living-cost grant depending on institution', 'Automatic consideration at some universities'],
    cd: ['Coverage, programmes, and deadlines vary by Danish institution', 'Not a central direct application scholarship'],
    req: ['Admission application to eligible programme', 'Scholarship consideration through institution process', 'Academic merit documents'],
    rdoc: ['Admission documents', 'Transcripts and diploma', 'Passport', 'CV or motivation documents if required'],
    ap: ['Choose a participating Danish institution', 'Apply for an eligible programme by admission deadline', 'Follow institution scholarship instructions', 'Await scholarship decision from the university'],
    sc: ['Academic excellence', 'Programme eligibility', 'Institution-specific ranking', 'Non-EU/EEA fee status'],
    tips: ['Check each Danish university page because scholarship availability is programme-specific', 'Some institutions consider eligible applicants automatically'],
    lr: ['English requirements depend on the host programme'],
    ec: ['All countries except listed exclusions'],
    ic: ['EU/EEA countries', 'Switzerland'],
    ecn: 'Official Danish university pages describe the scholarship as for highly qualified non-EU/EEA/non-Swiss applicants to selected programmes.',
    esu: 'https://www.sdu.dk/en/uddannelse/fees_and_funding/scholarships',
    url: 'https://www.sdu.dk/en/uddannelse/fees_and_funding/scholarships',
    osu: 'https://www.sdu.dk/en/uddannelse/fees_and_funding/scholarships',
    lv: LV,
    sn: 'Government scholarship allocation is administered by Danish institutions and is programme-specific; SDU is used as an official example source.',
    tags: ['Denmark', 'Government Scholarship', 'Non-EU', 'University Administered'],
    hc: 'Denmark',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-5',
    t: 'Finland Scholarships',
    on: 'Finnish University Scholarships for Non-EU/EEA Students',
    u: 'Finnish universities / Study in Finland guidance',
    c: 'Finland',
    cc: '🇫🇮',
    dl: ['Bachelor', 'Master'],
    ft: 'Tuition Only',
    d: '2026-01-22',
    ide: true,
    desc: 'Finland does not offer a central government scholarship for bachelor or master studies; individual Finnish universities offer tuition waivers or scholarships for fee-paying non-EU/EEA students.',
    el: ['Non-EU/EEA or non-Swiss tuition-fee liable applicant', 'Apply to an English-taught bachelor or master programme', 'Meet university-specific scholarship criteria'],
    ben: ['University tuition fee waiver or discount', 'Possible performance-based renewal or later-year scholarship depending on institution'],
    cd: ['Scholarship rules vary by university', 'Living costs are generally not covered by a central government scholarship'],
    req: ['Admission application through Studyinfo or university route', 'University scholarship application where required', 'Academic documents'],
    rdoc: ['Admission documents', 'Transcripts and diplomas', 'Passport', 'Language certificate', 'Motivation or scholarship form if required'],
    ap: ['Use Studyinfo or the university admission page', 'Check each university scholarship policy', 'Apply by the programme deadline', 'Accept and pay any required fees according to university rules'],
    sc: ['Academic merit', 'Tuition-fee liability', 'University-specific criteria', 'Study progress for renewal awards'],
    tips: ['Be cautious of claims about fully funded Finnish government bachelor/master scholarships', 'Use official Study in Finland and university pages'],
    lr: ['English language requirements depend on the host programme'],
    ec: ['All countries except listed exclusions'],
    ic: ['EU/EEA countries', 'Switzerland'],
    ecn: 'Official Study in Finland guidance states there are no governmental bachelor/master scholarships; university scholarships generally target non-EU/EEA fee-paying students.',
    esu: 'https://www.studyinfinland.fi/news-events/scholarship-facts',
    url: 'https://www.studyinfinland.fi/news-events/scholarship-facts',
    osu: 'https://www.studyinfinland.fi/news-events/scholarship-facts',
    lv: LV,
    sn: 'Included as a government-guidance entry, not as a direct central government scholarship; official source warns that fully funded Finnish government scholarship claims are misleading.',
    tags: ['Finland', 'Government Guidance', 'University Scholarships', 'Non-EU'],
    hc: 'Finland',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-6',
    t: 'Norway NORPART Scholarships',
    on: 'Norwegian Partnership Programme for Global Academic Cooperation (NORPART)',
    u: 'Norwegian Directorate for Higher Education and Skills',
    c: 'Norway',
    cc: '🇳🇴',
    dl: ['Master', 'PhD'],
    ft: 'Stipend',
    d: '2026-12-31',
    ide: true,
    desc: 'NORPART is a Norwegian government-funded institutional cooperation and mobility programme, not an open individual scholarship portal for all students.',
    el: ['Participant in an active NORPART project', 'Student mobility through a Norwegian institution and partner institution', 'Meet project-specific nomination rules'],
    ben: ['Mobility stipend through project where available', 'Support for exchange or project-linked study mobility', 'Amount varies by project'],
    cd: ['Funding is allocated to institutional projects', 'Students receive information through the relevant project or institution'],
    req: ['Nomination or participation in active NORPART project', 'Home and host institution approval', 'Project-specific documents'],
    rdoc: ['Institution nomination', 'Learning agreement or mobility documents', 'Passport', 'Project-specific forms'],
    ap: ['Check whether your institution is part of an active NORPART project', 'Follow nomination instructions from project coordinator', 'Complete host institution mobility documents', 'Sign grant documents if selected'],
    sc: ['Project participation', 'Institutional nomination', 'Academic fit', 'Mobility plan'],
    tips: ['Do not treat NORPART as a public application scholarship', 'Ask your university international office or project coordinator'],
    lr: ['Language requirements depend on the exchange or study project'],
    ec: ['Selected NORPART partner countries in the Global South'],
    ic: [],
    ecn: 'Official HK-dir source states NORPART supports institutional cooperation with selected partner countries in the Global South; student eligibility depends on active projects.',
    esu: 'https://hkdir.no/en/programmes-and-grant-schemes/norpart',
    url: 'https://hkdir.no/en/programmes-and-grant-schemes/norpart',
    osu: 'https://hkdir.no/en/programmes-and-grant-schemes/norpart',
    lv: LV,
    sn: 'Relevant official government-funded scheme, but not a direct central scholarship for individual applicants; HK-dir says no NORPART grants are currently open.',
    tags: ['Norway', 'NORPART', 'Government Funded', 'Mobility'],
    hc: 'Norway',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-7',
    t: 'Spain MAEC-AECID Scholarships',
    on: 'MAEC-AECID Scholarship Programme',
    u: 'AECID / Spanish Ministry of Foreign Affairs',
    c: 'Spain',
    cc: '🇪🇸',
    dl: ['Master'],
    ft: 'Stipend',
    d: '2027-03-13',
    ide: true,
    desc: 'MAEC-AECID scholarships are Spanish cooperation scholarships published through AECID calls, including programmes for citizens of Latin America, Africa, and the Philippines.',
    el: ['Citizen of countries listed in the active AECID call', 'Meet programme-specific academic and nationality requirements', 'Submit through AECID electronic office'],
    ben: ['Monthly stipend or grant support', 'Training or master programme support according to call', 'Insurance and travel conditions where listed'],
    cd: ['Benefits depend on programme annex and active call', 'Calls are published in AECID electronic office and BOE/BDNS references'],
    req: ['AECID electronic application', 'Eligible nationality', 'Academic documents', 'Programme-specific documents'],
    rdoc: ['Application form', 'Passport', 'Academic certificates', 'CV', 'Motivation or project documents', 'Admission documents if required'],
    ap: ['Open the active AECID procedure', 'Read the programme annex', 'Prepare required documents', 'Submit through the AECID electronic office before the deadline'],
    sc: ['Call-specific eligibility', 'Academic merit', 'Cooperation or cultural fit', 'Completeness of documents'],
    tips: ['Use the AECID electronic office, not third-party scholarship pages', 'Check the exact programme because country eligibility differs by call'],
    lr: ['Spanish or programme language requirements depend on the selected call'],
    ec: ['Countries listed in the active MAEC-AECID call'],
    ic: [],
    ecn: 'Official AECID procedures define eligibility by programme and call; the MASTER call is for citizens of Latin America, Africa, and the Philippines.',
    esu: 'https://www.aecid.gob.es/es/detalle-procedimiento-activo?_es_aecid_sede_procedimientos_ProcedimientoWebPortlet_id=workspace%3A%2F%2FSpacesStore%2Ff6d43a60-2c32-487c-92a3-ea03884d6e79',
    url: 'https://www.aecid.gob.es/',
    osu: 'https://www.aecid.gob.es/',
    lv: LV,
    sn: 'Direct Spanish government/AECID scholarship, but each call has its own country scope and deadline; next-cycle deadline is estimated from the latest MASTER procedure.',
    tags: ['Spain', 'AECID', 'Government', 'MAEC'],
    hc: 'Spain',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-8',
    t: 'Portugal Camões Scholarships',
    on: 'Camões, I.P. Scholarships',
    u: 'Camões Institute / Portuguese Ministry of Foreign Affairs',
    c: 'Portugal',
    cc: '🇵🇹',
    dl: ['Bachelor', 'Master', 'PhD'],
    ft: 'Stipend',
    d: '2026-05-18',
    desc: 'Camões, I.P. administers Portuguese cooperation and language/culture scholarships funded through the Portuguese state budget and Ministry of Foreign Affairs structures.',
    el: ['Eligible under Camões cooperation country or language/culture scholarship rules', 'Meet programme-specific academic requirements', 'Submit through the official Camões route'],
    ben: ['Monthly maintenance support', 'Tuition or fee support where listed', 'Installation, teaching material, or accommodation support depending on programme'],
    cd: ['Cooperation scholarships and language/culture scholarships have different rules', 'Benefits depend on programme and annual notice'],
    req: ['Camões services portal application or local authority submission', 'Eligible country/programme status', 'Academic documents'],
    rdoc: ['Application form', 'Passport', 'Academic certificates', 'CV', 'Programme-specific documents', 'Recommendation or local authority documents where required'],
    ap: ['Choose the relevant Camões scholarship programme', 'Check whether applications are online or through local authorities', 'Prepare documents under Camões regulations', 'Submit before the annual deadline'],
    sc: ['Programme fit', 'Country cooperation priorities', 'Academic record', 'Completeness of documents'],
    tips: ['Do not mix cooperation scholarships with language/culture scholarships', 'Check the Camões notice for the exact application route'],
    lr: ['Portuguese language requirements depend on scholarship programme'],
    ec: ['Angola', 'Cabo Verde', 'Colombia', 'Ethiopia', 'Guinea-Bissau', 'Mozambique', 'São Tomé and Príncipe', 'Senegal', 'Timor-Leste'],
    ic: [],
    ecn: 'Official Camões cooperation scholarship page lists the currently eligible countries for training in Portugal; language and culture programmes may have separate eligibility.',
    esu: 'https://www.instituto-camoes.pt/activity/o-que-fazemos/bolsas-estudo/bolsas-camoes/bolsas-cooperacao/formacao-em-portugal',
    url: 'https://www.instituto-camoes.pt/activity/o-que-fazemos/bolsas-estudo/bolsas-camoes',
    osu: 'https://www.instituto-camoes.pt/activity/o-que-fazemos/bolsas-estudo/bolsas-camoes',
    lv: LV,
    sn: 'Government-supported through Camões/Portuguese MFA; programme route differs between cooperation scholarships and Portuguese language/culture scholarships.',
    tags: ['Portugal', 'Camões', 'Government Supported', 'Cooperation'],
    hc: 'Portugal',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-9',
    t: 'Austria OeAD Scholarships',
    on: 'OeAD Grants and Scholarships',
    u: 'OeAD / Austrian Federal Ministry-supported programmes',
    c: 'Austria',
    cc: '🇦🇹',
    dl: ['Master', 'PhD', 'Postdoc'],
    ft: 'Stipend',
    d: '2027-03-01',
    ide: true,
    desc: 'OeAD administers Austrian grants and scholarships, including government-supported programmes whose eligibility and benefits vary by call in the grants.at database.',
    el: ['Meet nationality and academic rules for the selected grants.at call', 'Apply for an eligible Austrian study or research stay', 'Submit required documents by the call deadline'],
    ben: ['Monthly grant support', 'Insurance or travel support where listed', 'Study or research stay support according to call'],
    cd: ['Coverage is call-specific', 'Some Austrian Development Cooperation grants are limited to partner or developing countries'],
    req: ['Online application through grants.at or OeAD route', 'Eligible nationality for selected call', 'Academic documents', 'Research or study plan'],
    rdoc: ['Application form', 'CV', 'Academic certificates', 'Research proposal or study plan', 'References', 'Language proof where required'],
    ap: ['Search grants.at for the relevant OeAD grant', 'Read nationality and level requirements', 'Prepare call-specific documents', 'Submit through the official portal'],
    sc: ['Academic quality', 'Call fit', 'Development or research relevance', 'Host support where required'],
    tips: ['Use grants.at filters instead of assuming one OeAD scholarship covers all applicants', 'Check whether your country is eligible for the exact call'],
    lr: ['German or English requirements depend on the host programme and grant call'],
    ec: ['Countries listed in the selected OeAD/grants.at call'],
    ic: [],
    ecn: 'Official grants.at/OeAD calls define country eligibility by programme; applicant country must be verified in the selected official call.',
    esu: 'https://www.grants.at/',
    url: 'https://www.grants.at/',
    osu: 'https://oead.at/en/to-austria/grants-and-scholarships',
    lv: LV,
    sn: 'OeAD is an official Austrian agency administering multiple government-supported grants, not one single central scholarship with one country list.',
    tags: ['Austria', 'OeAD', 'Government Supported', 'grants.at'],
    hc: 'Austria',
    cat: 'Government',
    ca: '2026-05-04',
  },
  {
    id: 'gov3-10',
    t: 'Icelandic Government Scholarships',
    on: 'Icelandic Government Scholarships in Icelandic as a Second Language',
    u: 'Icelandic Ministry of Culture, Innovation and Higher Education / Árni Magnússon Institute',
    c: 'Iceland',
    cc: '🇮🇸',
    dl: ['Bachelor'],
    ft: 'Stipend',
    d: '2026-12-01',
    desc: 'The Icelandic Government awards scholarships for foreign university students to study the BA programme in Icelandic as a Second Language at the University of Iceland.',
    el: ['Student from a foreign university', 'Completed at least one year of university study in humanities', 'Basic knowledge of Icelandic', 'Apply separately to the University of Iceland if selected'],
    ben: ['University of Iceland registration fees', 'Monthly stipend for room and board', 'Scholarship period from September to May'],
    cd: ['Approximately 12 scholarships per year', 'Administered by the Árni Magnússon Institute for Icelandic Studies'],
    req: ['Special scholarship application form', 'Prior Icelandic knowledge', 'Humanities study background', 'Paper application by deadline'],
    rdoc: ['CV', 'Certified university transcripts and diplomas', 'Two academic recommendation letters', 'English proficiency certification', 'Passport copy'],
    ap: ['Download the official application form', 'Prepare documents in English, Icelandic, or another Scandinavian language', 'Mail the application by 1 December', 'Apply separately to University of Iceland by 1 February if awarded'],
    sc: ['Icelandic language preparation', 'Humanities background', 'Academic references', 'Fit for BA Icelandic as a Second Language'],
    tips: ['Email applications are not accepted', 'Complete Icelandic Online 1 and 2 before applying if you need preparation'],
    lr: ['Basic Icelandic required; English is used as a second language of instruction at the beginning'],
    ec: ['Foreign university students'],
    ic: [],
    ecn: 'Official Árni Magnússon Institute source states scholarships are for students coming from foreign universities to study Icelandic as a Second Language.',
    esu: 'https://www.arnastofnun.is/en/about-scholarship',
    url: 'https://www.arnastofnun.is/en/about-scholarship',
    osu: 'https://www.arnastofnun.is/en/about-scholarship',
    lv: LV,
    sn: 'Direct Icelandic government scholarship, but it is narrowly for Icelandic language studies rather than a general international degree scholarship.',
    tags: ['Iceland', 'Government', 'Icelandic Language', 'University of Iceland'],
    hc: 'Iceland',
    cat: 'Government',
    ca: '2026-05-04',
  },
];
